// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticatableMock creates a new instance of AuthenticatableMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatableMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatableMock {
	mock := &AuthenticatableMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthenticatableMock is an autogenerated mock type for the Authenticatable type
type AuthenticatableMock struct {
	mock.Mock
}

type AuthenticatableMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthenticatableMock) EXPECT() *AuthenticatableMock_Expecter {
	return &AuthenticatableMock_Expecter{mock: &_m.Mock}
}

// AuthID provides a mock function for the type AuthenticatableMock
func (_mock *AuthenticatableMock) AuthID() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthID")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// AuthenticatableMock_AuthID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthID'
type AuthenticatableMock_AuthID_Call struct {
	*mock.Call
}

// AuthID is a helper method to define mock.On call
func (_e *AuthenticatableMock_Expecter) AuthID() *AuthenticatableMock_AuthID_Call {
	return &AuthenticatableMock_AuthID_Call{Call: _e.mock.On("AuthID")}
}

func (_c *AuthenticatableMock_AuthID_Call) Run(run func()) *AuthenticatableMock_AuthID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticatableMock_AuthID_Call) Return(bytes []byte) *AuthenticatableMock_AuthID_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *AuthenticatableMock_AuthID_Call) RunAndReturn(run func() []byte) *AuthenticatableMock_AuthID_Call {
	_c.Call.Return(run)
	return _c
}

// AuthPassword provides a mock function for the type AuthenticatableMock
func (_mock *AuthenticatableMock) AuthPassword() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthPassword")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// AuthenticatableMock_AuthPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthPassword'
type AuthenticatableMock_AuthPassword_Call struct {
	*mock.Call
}

// AuthPassword is a helper method to define mock.On call
func (_e *AuthenticatableMock_Expecter) AuthPassword() *AuthenticatableMock_AuthPassword_Call {
	return &AuthenticatableMock_AuthPassword_Call{Call: _e.mock.On("AuthPassword")}
}

func (_c *AuthenticatableMock_AuthPassword_Call) Run(run func()) *AuthenticatableMock_AuthPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthenticatableMock_AuthPassword_Call) Return(bytes []byte) *AuthenticatableMock_AuthPassword_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *AuthenticatableMock_AuthPassword_Call) RunAndReturn(run func() []byte) *AuthenticatableMock_AuthPassword_Call {
	_c.Call.Return(run)
	return _c
}
