// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewAuthProviderMock creates a new instance of AuthProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthProviderMock[User contract.Authenticatable](t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProviderMock[User] {
	mock := &AuthProviderMock[User]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthProviderMock is an autogenerated mock type for the AuthProvider type
type AuthProviderMock[User contract.Authenticatable] struct {
	mock.Mock
}

type AuthProviderMock_Expecter[User contract.Authenticatable] struct {
	mock *mock.Mock
}

func (_m *AuthProviderMock[User]) EXPECT() *AuthProviderMock_Expecter[User] {
	return &AuthProviderMock_Expecter[User]{mock: &_m.Mock}
}

// RetrieveByCredentials provides a mock function for the type AuthProviderMock
func (_mock *AuthProviderMock[User]) RetrieveByCredentials(ctx context.Context, identifier []byte) (User, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveByCredentials")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (User, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) User); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthProviderMock_RetrieveByCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveByCredentials'
type AuthProviderMock_RetrieveByCredentials_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// RetrieveByCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier []byte
func (_e *AuthProviderMock_Expecter[User]) RetrieveByCredentials(ctx interface{}, identifier interface{}) *AuthProviderMock_RetrieveByCredentials_Call[User] {
	return &AuthProviderMock_RetrieveByCredentials_Call[User]{Call: _e.mock.On("RetrieveByCredentials", ctx, identifier)}
}

func (_c *AuthProviderMock_RetrieveByCredentials_Call[User]) Run(run func(ctx context.Context, identifier []byte)) *AuthProviderMock_RetrieveByCredentials_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthProviderMock_RetrieveByCredentials_Call[User]) Return(v User, err error) *AuthProviderMock_RetrieveByCredentials_Call[User] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthProviderMock_RetrieveByCredentials_Call[User]) RunAndReturn(run func(ctx context.Context, identifier []byte) (User, error)) *AuthProviderMock_RetrieveByCredentials_Call[User] {
	_c.Call.Return(run)
	return _c
}

// UserByID provides a mock function for the type AuthProviderMock
func (_mock *AuthProviderMock[User]) UserByID(ctx context.Context, id []byte) (User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserByID")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthProviderMock_UserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByID'
type AuthProviderMock_UserByID_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// UserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id []byte
func (_e *AuthProviderMock_Expecter[User]) UserByID(ctx interface{}, id interface{}) *AuthProviderMock_UserByID_Call[User] {
	return &AuthProviderMock_UserByID_Call[User]{Call: _e.mock.On("UserByID", ctx, id)}
}

func (_c *AuthProviderMock_UserByID_Call[User]) Run(run func(ctx context.Context, id []byte)) *AuthProviderMock_UserByID_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthProviderMock_UserByID_Call[User]) Return(v User, err error) *AuthProviderMock_UserByID_Call[User] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthProviderMock_UserByID_Call[User]) RunAndReturn(run func(ctx context.Context, id []byte) (User, error)) *AuthProviderMock_UserByID_Call[User] {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type AuthProviderMock
func (_mock *AuthProviderMock[User]) Validate(ctx context.Context, user User, password []byte) bool {
	ret := _mock.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, User, []byte) bool); ok {
		r0 = returnFunc(ctx, user, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// AuthProviderMock_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type AuthProviderMock_Validate_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - user User
//   - password []byte
func (_e *AuthProviderMock_Expecter[User]) Validate(ctx interface{}, user interface{}, password interface{}) *AuthProviderMock_Validate_Call[User] {
	return &AuthProviderMock_Validate_Call[User]{Call: _e.mock.On("Validate", ctx, user, password)}
}

func (_c *AuthProviderMock_Validate_Call[User]) Run(run func(ctx context.Context, user User, password []byte)) *AuthProviderMock_Validate_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 User
		if args[1] != nil {
			arg1 = args[1].(User)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthProviderMock_Validate_Call[User]) Return(b bool) *AuthProviderMock_Validate_Call[User] {
	_c.Call.Return(b)
	return _c
}

func (_c *AuthProviderMock_Validate_Call[User]) RunAndReturn(run func(ctx context.Context, user User, password []byte) bool) *AuthProviderMock_Validate_Call[User] {
	_c.Call.Return(run)
	return _c
}
