// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
	"net/http"
)

// NewAuthGuardMock creates a new instance of AuthGuardMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthGuardMock[User contract.Authenticatable](t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthGuardMock[User] {
	mock := &AuthGuardMock[User]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthGuardMock is an autogenerated mock type for the AuthGuard type
type AuthGuardMock[User contract.Authenticatable] struct {
	mock.Mock
}

type AuthGuardMock_Expecter[User contract.Authenticatable] struct {
	mock *mock.Mock
}

func (_m *AuthGuardMock[User]) EXPECT() *AuthGuardMock_Expecter[User] {
	return &AuthGuardMock_Expecter[User]{mock: &_m.Mock}
}

// Attempt provides a mock function for the type AuthGuardMock
func (_mock *AuthGuardMock[User]) Attempt(w http.ResponseWriter, r *http.Request, identifier []byte, password []byte) (User, error) {
	ret := _mock.Called(w, r, identifier, password)

	if len(ret) == 0 {
		panic("no return value specified for Attempt")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, []byte, []byte) (User, error)); ok {
		return returnFunc(w, r, identifier, password)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, []byte, []byte) User); ok {
		r0 = returnFunc(w, r, identifier, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, []byte, []byte) error); ok {
		r1 = returnFunc(w, r, identifier, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthGuardMock_Attempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attempt'
type AuthGuardMock_Attempt_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// Attempt is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - identifier []byte
//   - password []byte
func (_e *AuthGuardMock_Expecter[User]) Attempt(w interface{}, r interface{}, identifier interface{}, password interface{}) *AuthGuardMock_Attempt_Call[User] {
	return &AuthGuardMock_Attempt_Call[User]{Call: _e.mock.On("Attempt", w, r, identifier, password)}
}

func (_c *AuthGuardMock_Attempt_Call[User]) Run(run func(w http.ResponseWriter, r *http.Request, identifier []byte, password []byte)) *AuthGuardMock_Attempt_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthGuardMock_Attempt_Call[User]) Return(v User, err error) *AuthGuardMock_Attempt_Call[User] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthGuardMock_Attempt_Call[User]) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, identifier []byte, password []byte) (User, error)) *AuthGuardMock_Attempt_Call[User] {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type AuthGuardMock
func (_mock *AuthGuardMock[User]) Check(r *http.Request) (bool, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (bool, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) bool); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthGuardMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type AuthGuardMock_Check_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - r *http.Request
func (_e *AuthGuardMock_Expecter[User]) Check(r interface{}) *AuthGuardMock_Check_Call[User] {
	return &AuthGuardMock_Check_Call[User]{Call: _e.mock.On("Check", r)}
}

func (_c *AuthGuardMock_Check_Call[User]) Run(run func(r *http.Request)) *AuthGuardMock_Check_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthGuardMock_Check_Call[User]) Return(b bool, err error) *AuthGuardMock_Check_Call[User] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AuthGuardMock_Check_Call[User]) RunAndReturn(run func(r *http.Request) (bool, error)) *AuthGuardMock_Check_Call[User] {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthGuardMock
func (_mock *AuthGuardMock[User]) Login(w http.ResponseWriter, r *http.Request, user User) error {
	ret := _mock.Called(w, r, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, User) error); ok {
		r0 = returnFunc(w, r, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthGuardMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthGuardMock_Login_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - user User
func (_e *AuthGuardMock_Expecter[User]) Login(w interface{}, r interface{}, user interface{}) *AuthGuardMock_Login_Call[User] {
	return &AuthGuardMock_Login_Call[User]{Call: _e.mock.On("Login", w, r, user)}
}

func (_c *AuthGuardMock_Login_Call[User]) Run(run func(w http.ResponseWriter, r *http.Request, user User)) *AuthGuardMock_Login_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 User
		if args[2] != nil {
			arg2 = args[2].(User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthGuardMock_Login_Call[User]) Return(err error) *AuthGuardMock_Login_Call[User] {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthGuardMock_Login_Call[User]) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, user User) error) *AuthGuardMock_Login_Call[User] {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthGuardMock
func (_mock *AuthGuardMock[User]) Logout(w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthGuardMock_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthGuardMock_Logout_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthGuardMock_Expecter[User]) Logout(w interface{}, r interface{}) *AuthGuardMock_Logout_Call[User] {
	return &AuthGuardMock_Logout_Call[User]{Call: _e.mock.On("Logout", w, r)}
}

func (_c *AuthGuardMock_Logout_Call[User]) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthGuardMock_Logout_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthGuardMock_Logout_Call[User]) Return(err error) *AuthGuardMock_Logout_Call[User] {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthGuardMock_Logout_Call[User]) RunAndReturn(run func(w http.ResponseWriter, r *http.Request) error) *AuthGuardMock_Logout_Call[User] {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type AuthGuardMock
func (_mock *AuthGuardMock[User]) User(r *http.Request) (User, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (User, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) User); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthGuardMock_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type AuthGuardMock_User_Call[User contract.Authenticatable] struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - r *http.Request
func (_e *AuthGuardMock_Expecter[User]) User(r interface{}) *AuthGuardMock_User_Call[User] {
	return &AuthGuardMock_User_Call[User]{Call: _e.mock.On("User", r)}
}

func (_c *AuthGuardMock_User_Call[User]) Run(run func(r *http.Request)) *AuthGuardMock_User_Call[User] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthGuardMock_User_Call[User]) Return(v User, err error) *AuthGuardMock_User_Call[User] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AuthGuardMock_User_Call[User]) RunAndReturn(run func(r *http.Request) (User, error)) *AuthGuardMock_User_Call[User] {
	_c.Call.Return(run)
	return _c
}
