// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewCacheMock creates a new instance of CacheMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheMock {
	mock := &CacheMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheMock is an autogenerated mock type for the Cache type
type CacheMock struct {
	mock.Mock
}

type CacheMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheMock) EXPECT() *CacheMock_Expecter {
	return &CacheMock_Expecter{mock: &_m.Mock}
}

// Decrement provides a mock function for the type CacheMock
func (_mock *CacheMock) Decrement(ctx context.Context, key string, by int64) (int64, error) {
	ret := _mock.Called(ctx, key, by)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, by)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, by)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, by)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type CacheMock_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - by int64
func (_e *CacheMock_Expecter) Decrement(ctx interface{}, key interface{}, by interface{}) *CacheMock_Decrement_Call {
	return &CacheMock_Decrement_Call{Call: _e.mock.On("Decrement", ctx, key, by)}
}

func (_c *CacheMock_Decrement_Call) Run(run func(ctx context.Context, key string, by int64)) *CacheMock_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_Decrement_Call) Return(n int64, err error) *CacheMock_Decrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheMock_Decrement_Call) RunAndReturn(run func(ctx context.Context, key string, by int64) (int64, error)) *CacheMock_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CacheMock
func (_mock *CacheMock) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CacheMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Delete(ctx interface{}, key interface{}) *CacheMock_Delete_Call {
	return &CacheMock_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *CacheMock_Delete_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Delete_Call) Return(err error) *CacheMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *CacheMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Forever provides a mock function for the type CacheMock
func (_mock *CacheMock) Forever(ctx context.Context, key string, value any) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Forever")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Forever_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forever'
type CacheMock_Forever_Call struct {
	*mock.Call
}

// Forever is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
func (_e *CacheMock_Expecter) Forever(ctx interface{}, key interface{}, value interface{}) *CacheMock_Forever_Call {
	return &CacheMock_Forever_Call{Call: _e.mock.On("Forever", ctx, key, value)}
}

func (_c *CacheMock_Forever_Call) Run(run func(ctx context.Context, key string, value any)) *CacheMock_Forever_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_Forever_Call) Return(err error) *CacheMock_Forever_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Forever_Call) RunAndReturn(run func(ctx context.Context, key string, value any) error) *CacheMock_Forever_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CacheMock
func (_mock *CacheMock) Get(ctx context.Context, key string) (any, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Get(ctx interface{}, key interface{}) *CacheMock_Get_Call {
	return &CacheMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheMock_Get_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Get_Call) Return(v any, err error) *CacheMock_Get_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *CacheMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (any, error)) *CacheMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type CacheMock
func (_mock *CacheMock) Has(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type CacheMock_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Has(ctx interface{}, key interface{}) *CacheMock_Has_Call {
	return &CacheMock_Has_Call{Call: _e.mock.On("Has", ctx, key)}
}

func (_c *CacheMock_Has_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Has_Call) Return(b bool, err error) *CacheMock_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheMock_Has_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *CacheMock_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type CacheMock
func (_mock *CacheMock) Increment(ctx context.Context, key string, by int64) (int64, error) {
	ret := _mock.Called(ctx, key, by)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, by)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, by)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, by)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type CacheMock_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - by int64
func (_e *CacheMock_Expecter) Increment(ctx interface{}, key interface{}, by interface{}) *CacheMock_Increment_Call {
	return &CacheMock_Increment_Call{Call: _e.mock.On("Increment", ctx, key, by)}
}

func (_c *CacheMock_Increment_Call) Run(run func(ctx context.Context, key string, by int64)) *CacheMock_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_Increment_Call) Return(n int64, err error) *CacheMock_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheMock_Increment_Call) RunAndReturn(run func(ctx context.Context, key string, by int64) (int64, error)) *CacheMock_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type CacheMock
func (_mock *CacheMock) Pull(ctx context.Context, key string) (any, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type CacheMock_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Pull(ctx interface{}, key interface{}) *CacheMock_Pull_Call {
	return &CacheMock_Pull_Call{Call: _e.mock.On("Pull", ctx, key)}
}

func (_c *CacheMock_Pull_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Pull_Call) Return(v any, err error) *CacheMock_Pull_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *CacheMock_Pull_Call) RunAndReturn(run func(ctx context.Context, key string) (any, error)) *CacheMock_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type CacheMock
func (_mock *CacheMock) Put(ctx context.Context, key string, value any, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type CacheMock_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *CacheMock_Expecter) Put(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *CacheMock_Put_Call {
	return &CacheMock_Put_Call{Call: _e.mock.On("Put", ctx, key, value, ttl)}
}

func (_c *CacheMock_Put_Call) Run(run func(ctx context.Context, key string, value any, ttl time.Duration)) *CacheMock_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheMock_Put_Call) Return(err error) *CacheMock_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Put_Call) RunAndReturn(run func(ctx context.Context, key string, value any, ttl time.Duration) error) *CacheMock_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Remember provides a mock function for the type CacheMock
func (_mock *CacheMock) Remember(ctx context.Context, key string, ttl time.Duration, compute func() (any, error)) (any, error) {
	ret := _mock.Called(ctx, key, ttl, compute)

	if len(ret) == 0 {
		panic("no return value specified for Remember")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func() (any, error)) (any, error)); ok {
		return returnFunc(ctx, key, ttl, compute)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func() (any, error)) any); ok {
		r0 = returnFunc(ctx, key, ttl, compute)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, func() (any, error)) error); ok {
		r1 = returnFunc(ctx, key, ttl, compute)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Remember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remember'
type CacheMock_Remember_Call struct {
	*mock.Call
}

// Remember is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - compute func() (any, error)
func (_e *CacheMock_Expecter) Remember(ctx interface{}, key interface{}, ttl interface{}, compute interface{}) *CacheMock_Remember_Call {
	return &CacheMock_Remember_Call{Call: _e.mock.On("Remember", ctx, key, ttl, compute)}
}

func (_c *CacheMock_Remember_Call) Run(run func(ctx context.Context, key string, ttl time.Duration, compute func() (any, error))) *CacheMock_Remember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 func() (any, error)
		if args[3] != nil {
			arg3 = args[3].(func() (any, error))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheMock_Remember_Call) Return(v any, err error) *CacheMock_Remember_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *CacheMock_Remember_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, compute func() (any, error)) (any, error)) *CacheMock_Remember_Call {
	_c.Call.Return(run)
	return _c
}

// RememberForever provides a mock function for the type CacheMock
func (_mock *CacheMock) RememberForever(ctx context.Context, key string, compute func() (any, error)) (any, error) {
	ret := _mock.Called(ctx, key, compute)

	if len(ret) == 0 {
		panic("no return value specified for RememberForever")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func() (any, error)) (any, error)); ok {
		return returnFunc(ctx, key, compute)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func() (any, error)) any); ok {
		r0 = returnFunc(ctx, key, compute)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, func() (any, error)) error); ok {
		r1 = returnFunc(ctx, key, compute)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_RememberForever_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RememberForever'
type CacheMock_RememberForever_Call struct {
	*mock.Call
}

// RememberForever is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - compute func() (any, error)
func (_e *CacheMock_Expecter) RememberForever(ctx interface{}, key interface{}, compute interface{}) *CacheMock_RememberForever_Call {
	return &CacheMock_RememberForever_Call{Call: _e.mock.On("RememberForever", ctx, key, compute)}
}

func (_c *CacheMock_RememberForever_Call) Run(run func(ctx context.Context, key string, compute func() (any, error))) *CacheMock_RememberForever_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func() (any, error)
		if args[2] != nil {
			arg2 = args[2].(func() (any, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_RememberForever_Call) Return(v any, err error) *CacheMock_RememberForever_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *CacheMock_RememberForever_Call) RunAndReturn(run func(ctx context.Context, key string, compute func() (any, error)) (any, error)) *CacheMock_RememberForever_Call {
	_c.Call.Return(run)
	return _c
}
