// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewCacheDriverMock creates a new instance of CacheDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheDriverMock {
	mock := &CacheDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheDriverMock is an autogenerated mock type for the CacheDriver type
type CacheDriverMock struct {
	mock.Mock
}

type CacheDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheDriverMock) EXPECT() *CacheDriverMock_Expecter {
	return &CacheDriverMock_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Add(ctx context.Context, key string, value []byte, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, value, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, value, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CacheDriverMock_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *CacheDriverMock_Expecter) Add(ctx any, key any, value any, ttl any) *CacheDriverMock_Add_Call {
	return &CacheDriverMock_Add_Call{Call: _e.mock.On("Add", ctx, key, value, ttl)}
}

func (_c *CacheDriverMock_Add_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *CacheDriverMock_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Add_Call) Return(b bool, err error) *CacheDriverMock_Add_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheDriverMock_Add_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, ttl time.Duration) (bool, error)) *CacheDriverMock_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Decrement provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Decrement(ctx context.Context, key string, delta int64) (int64, error) {
	ret := _mock.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, delta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type CacheDriverMock_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
func (_e *CacheDriverMock_Expecter) Decrement(ctx any, key any, delta any) *CacheDriverMock_Decrement_Call {
	return &CacheDriverMock_Decrement_Call{Call: _e.mock.On("Decrement", ctx, key, delta)}
}

func (_c *CacheDriverMock_Decrement_Call) Run(run func(ctx context.Context, key string, delta int64)) *CacheDriverMock_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Decrement_Call) Return(n int64, err error) *CacheDriverMock_Decrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheDriverMock_Decrement_Call) RunAndReturn(run func(ctx context.Context, key string, delta int64) (int64, error)) *CacheDriverMock_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheDriverMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CacheDriverMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Delete(ctx any, key any) *CacheDriverMock_Delete_Call {
	return &CacheDriverMock_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *CacheDriverMock_Delete_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Delete_Call) Return(err error) *CacheDriverMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheDriverMock_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *CacheDriverMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheDriverMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Get(ctx any, key any) *CacheDriverMock_Get_Call {
	return &CacheDriverMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheDriverMock_Get_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Get_Call) Return(bytes []byte, err error) *CacheDriverMock_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *CacheDriverMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *CacheDriverMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Has(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type CacheDriverMock_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Has(ctx any, key any) *CacheDriverMock_Has_Call {
	return &CacheDriverMock_Has_Call{Call: _e.mock.On("Has", ctx, key)}
}

func (_c *CacheDriverMock_Has_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Has_Call) Return(b bool, err error) *CacheDriverMock_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheDriverMock_Has_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *CacheDriverMock_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Increment(ctx context.Context, key string, delta int64) (int64, error) {
	ret := _mock.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, delta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type CacheDriverMock_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
func (_e *CacheDriverMock_Expecter) Increment(ctx any, key any, delta any) *CacheDriverMock_Increment_Call {
	return &CacheDriverMock_Increment_Call{Call: _e.mock.On("Increment", ctx, key, delta)}
}

func (_c *CacheDriverMock_Increment_Call) Run(run func(ctx context.Context, key string, delta int64)) *CacheDriverMock_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Increment_Call) Return(n int64, err error) *CacheDriverMock_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheDriverMock_Increment_Call) RunAndReturn(run func(ctx context.Context, key string, delta int64) (int64, error)) *CacheDriverMock_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Put(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheDriverMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type CacheDriverMock_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *CacheDriverMock_Expecter) Put(ctx any, key any, value any, ttl any) *CacheDriverMock_Put_Call {
	return &CacheDriverMock_Put_Call{Call: _e.mock.On("Put", ctx, key, value, ttl)}
}

func (_c *CacheDriverMock_Put_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *CacheDriverMock_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Put_Call) Return(err error) *CacheDriverMock_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheDriverMock_Put_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, ttl time.Duration) error) *CacheDriverMock_Put_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) TTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type CacheDriverMock_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) TTL(ctx any, key any) *CacheDriverMock_TTL_Call {
	return &CacheDriverMock_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *CacheDriverMock_TTL_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_TTL_Call) Return(duration time.Duration, err error) *CacheDriverMock_TTL_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *CacheDriverMock_TTL_Call) RunAndReturn(run func(ctx context.Context, key string) (time.Duration, error)) *CacheDriverMock_TTL_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheCounterWithTTLMock creates a new instance of CacheCounterWithTTLMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheCounterWithTTLMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheCounterWithTTLMock {
	mock := &CacheCounterWithTTLMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheCounterWithTTLMock is an autogenerated mock type for the CacheCounterWithTTL type
type CacheCounterWithTTLMock struct {
	mock.Mock
}

type CacheCounterWithTTLMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheCounterWithTTLMock) EXPECT() *CacheCounterWithTTLMock_Expecter {
	return &CacheCounterWithTTLMock_Expecter{mock: &_m.Mock}
}

// IncrementWithTTL provides a mock function for the type CacheCounterWithTTLMock
func (_mock *CacheCounterWithTTLMock) IncrementWithTTL(ctx context.Context, key string, delta int64, ttl time.Duration) (int64, time.Duration, error) {
	ret := _mock.Called(ctx, key, delta, ttl)

	if len(ret) == 0 {
		panic("no return value specified for IncrementWithTTL")
	}

	var r0 int64
	var r1 time.Duration
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) (int64, time.Duration, error)); ok {
		return returnFunc(ctx, key, delta, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, time.Duration) int64); ok {
		r0 = returnFunc(ctx, key, delta, ttl)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, time.Duration) time.Duration); ok {
		r1 = returnFunc(ctx, key, delta, ttl)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int64, time.Duration) error); ok {
		r2 = returnFunc(ctx, key, delta, ttl)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// CacheCounterWithTTLMock_IncrementWithTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementWithTTL'
type CacheCounterWithTTLMock_IncrementWithTTL_Call struct {
	*mock.Call
}

// IncrementWithTTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
//   - ttl time.Duration
func (_e *CacheCounterWithTTLMock_Expecter) IncrementWithTTL(ctx any, key any, delta any, ttl any) *CacheCounterWithTTLMock_IncrementWithTTL_Call {
	return &CacheCounterWithTTLMock_IncrementWithTTL_Call{Call: _e.mock.On("IncrementWithTTL", ctx, key, delta, ttl)}
}

func (_c *CacheCounterWithTTLMock_IncrementWithTTL_Call) Run(run func(ctx context.Context, key string, delta int64, ttl time.Duration)) *CacheCounterWithTTLMock_IncrementWithTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheCounterWithTTLMock_IncrementWithTTL_Call) Return(n int64, duration time.Duration, err error) *CacheCounterWithTTLMock_IncrementWithTTL_Call {
	_c.Call.Return(n, duration, err)
	return _c
}

func (_c *CacheCounterWithTTLMock_IncrementWithTTL_Call) RunAndReturn(run func(ctx context.Context, key string, delta int64, ttl time.Duration) (int64, time.Duration, error)) *CacheCounterWithTTLMock_IncrementWithTTL_Call {
	_c.Call.Return(run)
	return _c
}
