// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewCacheDriverMock creates a new instance of CacheDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheDriverMock {
	mock := &CacheDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheDriverMock is an autogenerated mock type for the CacheDriver type
type CacheDriverMock struct {
	mock.Mock
}

type CacheDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheDriverMock) EXPECT() *CacheDriverMock_Expecter {
	return &CacheDriverMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheDriverMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CacheDriverMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Delete(ctx interface{}, key interface{}) *CacheDriverMock_Delete_Call {
	return &CacheDriverMock_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *CacheDriverMock_Delete_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Delete_Call) Return(err error) *CacheDriverMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheDriverMock_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *CacheDriverMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheDriverMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Get(ctx interface{}, key interface{}) *CacheDriverMock_Get_Call {
	return &CacheDriverMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheDriverMock_Get_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Get_Call) Return(bytes []byte, err error) *CacheDriverMock_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *CacheDriverMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *CacheDriverMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Has(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheDriverMock_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type CacheDriverMock_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheDriverMock_Expecter) Has(ctx interface{}, key interface{}) *CacheDriverMock_Has_Call {
	return &CacheDriverMock_Has_Call{Call: _e.mock.On("Has", ctx, key)}
}

func (_c *CacheDriverMock_Has_Call) Run(run func(ctx context.Context, key string)) *CacheDriverMock_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Has_Call) Return(b bool, err error) *CacheDriverMock_Has_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheDriverMock_Has_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *CacheDriverMock_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type CacheDriverMock
func (_mock *CacheDriverMock) Put(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheDriverMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type CacheDriverMock_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - ttl time.Duration
func (_e *CacheDriverMock_Expecter) Put(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *CacheDriverMock_Put_Call {
	return &CacheDriverMock_Put_Call{Call: _e.mock.On("Put", ctx, key, value, ttl)}
}

func (_c *CacheDriverMock_Put_Call) Run(run func(ctx context.Context, key string, value []byte, ttl time.Duration)) *CacheDriverMock_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheDriverMock_Put_Call) Return(err error) *CacheDriverMock_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheDriverMock_Put_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, ttl time.Duration) error) *CacheDriverMock_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheCounterMock creates a new instance of CacheCounterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheCounterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheCounterMock {
	mock := &CacheCounterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheCounterMock is an autogenerated mock type for the CacheCounter type
type CacheCounterMock struct {
	mock.Mock
}

type CacheCounterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheCounterMock) EXPECT() *CacheCounterMock_Expecter {
	return &CacheCounterMock_Expecter{mock: &_m.Mock}
}

// Decrement provides a mock function for the type CacheCounterMock
func (_mock *CacheCounterMock) Decrement(ctx context.Context, key string, delta int64) (int64, error) {
	ret := _mock.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, delta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheCounterMock_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type CacheCounterMock_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
func (_e *CacheCounterMock_Expecter) Decrement(ctx interface{}, key interface{}, delta interface{}) *CacheCounterMock_Decrement_Call {
	return &CacheCounterMock_Decrement_Call{Call: _e.mock.On("Decrement", ctx, key, delta)}
}

func (_c *CacheCounterMock_Decrement_Call) Run(run func(ctx context.Context, key string, delta int64)) *CacheCounterMock_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheCounterMock_Decrement_Call) Return(n int64, err error) *CacheCounterMock_Decrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheCounterMock_Decrement_Call) RunAndReturn(run func(ctx context.Context, key string, delta int64) (int64, error)) *CacheCounterMock_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type CacheCounterMock
func (_mock *CacheCounterMock) Increment(ctx context.Context, key string, delta int64) (int64, error) {
	ret := _mock.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, key, delta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheCounterMock_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type CacheCounterMock_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - delta int64
func (_e *CacheCounterMock_Expecter) Increment(ctx interface{}, key interface{}, delta interface{}) *CacheCounterMock_Increment_Call {
	return &CacheCounterMock_Increment_Call{Call: _e.mock.On("Increment", ctx, key, delta)}
}

func (_c *CacheCounterMock_Increment_Call) Run(run func(ctx context.Context, key string, delta int64)) *CacheCounterMock_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheCounterMock_Increment_Call) Return(n int64, err error) *CacheCounterMock_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheCounterMock_Increment_Call) RunAndReturn(run func(ctx context.Context, key string, delta int64) (int64, error)) *CacheCounterMock_Increment_Call {
	_c.Call.Return(run)
	return _c
}
