// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewConfigurationDriverMock creates a new instance of ConfigurationDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationDriverMock {
	mock := &ConfigurationDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurationDriverMock is an autogenerated mock type for the ConfigurationDriver type
type ConfigurationDriverMock struct {
	mock.Mock
}

type ConfigurationDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigurationDriverMock) EXPECT() *ConfigurationDriverMock_Expecter {
	return &ConfigurationDriverMock_Expecter{mock: &_m.Mock}
}

// Has provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Has(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConfigurationDriverMock_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type ConfigurationDriverMock_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key string
func (_e *ConfigurationDriverMock_Expecter) Has(key any) *ConfigurationDriverMock_Has_Call {
	return &ConfigurationDriverMock_Has_Call{Call: _e.mock.On("Has", key)}
}

func (_c *ConfigurationDriverMock_Has_Call) Run(run func(key string)) *ConfigurationDriverMock_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigurationDriverMock_Has_Call) Return(b bool) *ConfigurationDriverMock_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConfigurationDriverMock_Has_Call) RunAndReturn(run func(key string) bool) *ConfigurationDriverMock_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Unmarshal(key string, dest any) error {
	ret := _mock.Called(key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConfigurationDriverMock_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type ConfigurationDriverMock_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - key string
//   - dest any
func (_e *ConfigurationDriverMock_Expecter) Unmarshal(key any, dest any) *ConfigurationDriverMock_Unmarshal_Call {
	return &ConfigurationDriverMock_Unmarshal_Call{Call: _e.mock.On("Unmarshal", key, dest)}
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) Run(run func(key string, dest any)) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) Return(err error) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) RunAndReturn(run func(key string, dest any) error) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}
