// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewConfigurationDriverMock creates a new instance of ConfigurationDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationDriverMock {
	mock := &ConfigurationDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurationDriverMock is an autogenerated mock type for the ConfigurationDriver type
type ConfigurationDriverMock struct {
	mock.Mock
}

type ConfigurationDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigurationDriverMock) EXPECT() *ConfigurationDriverMock_Expecter {
	return &ConfigurationDriverMock_Expecter{mock: &_m.Mock}
}

// Delimiter provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Delimiter() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delimiter")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigurationDriverMock_Delimiter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delimiter'
type ConfigurationDriverMock_Delimiter_Call struct {
	*mock.Call
}

// Delimiter is a helper method to define mock.On call
func (_e *ConfigurationDriverMock_Expecter) Delimiter() *ConfigurationDriverMock_Delimiter_Call {
	return &ConfigurationDriverMock_Delimiter_Call{Call: _e.mock.On("Delimiter")}
}

func (_c *ConfigurationDriverMock_Delimiter_Call) Run(run func()) *ConfigurationDriverMock_Delimiter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigurationDriverMock_Delimiter_Call) Return(s string) *ConfigurationDriverMock_Delimiter_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigurationDriverMock_Delimiter_Call) RunAndReturn(run func() string) *ConfigurationDriverMock_Delimiter_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Extend(providers ...contract.ConfigurationProvider) error {
	var tmpRet mock.Arguments
	if len(providers) > 0 {
		tmpRet = _mock.Called(providers)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...contract.ConfigurationProvider) error); ok {
		r0 = returnFunc(providers...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConfigurationDriverMock_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type ConfigurationDriverMock_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
//   - providers ...contract.ConfigurationProvider
func (_e *ConfigurationDriverMock_Expecter) Extend(providers ...any) *ConfigurationDriverMock_Extend_Call {
	return &ConfigurationDriverMock_Extend_Call{Call: _e.mock.On("Extend",
		append([]any{}, providers...)...)}
}

func (_c *ConfigurationDriverMock_Extend_Call) Run(run func(providers ...contract.ConfigurationProvider)) *ConfigurationDriverMock_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []contract.ConfigurationProvider
		var variadicArgs []contract.ConfigurationProvider
		if len(args) > 0 {
			variadicArgs = args[0].([]contract.ConfigurationProvider)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *ConfigurationDriverMock_Extend_Call) Return(err error) *ConfigurationDriverMock_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConfigurationDriverMock_Extend_Call) RunAndReturn(run func(providers ...contract.ConfigurationProvider) error) *ConfigurationDriverMock_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Has(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConfigurationDriverMock_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type ConfigurationDriverMock_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key string
func (_e *ConfigurationDriverMock_Expecter) Has(key any) *ConfigurationDriverMock_Has_Call {
	return &ConfigurationDriverMock_Has_Call{Call: _e.mock.On("Has", key)}
}

func (_c *ConfigurationDriverMock_Has_Call) Run(run func(key string)) *ConfigurationDriverMock_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigurationDriverMock_Has_Call) Return(b bool) *ConfigurationDriverMock_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConfigurationDriverMock_Has_Call) RunAndReturn(run func(key string) bool) *ConfigurationDriverMock_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type ConfigurationDriverMock
func (_mock *ConfigurationDriverMock) Unmarshal(key string, dest any) error {
	ret := _mock.Called(key, dest)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(key, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConfigurationDriverMock_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type ConfigurationDriverMock_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - key string
//   - dest any
func (_e *ConfigurationDriverMock_Expecter) Unmarshal(key any, dest any) *ConfigurationDriverMock_Unmarshal_Call {
	return &ConfigurationDriverMock_Unmarshal_Call{Call: _e.mock.On("Unmarshal", key, dest)}
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) Run(run func(key string, dest any)) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) Return(err error) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConfigurationDriverMock_Unmarshal_Call) RunAndReturn(run func(key string, dest any) error) *ConfigurationDriverMock_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigurationProviderMock creates a new instance of ConfigurationProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationProviderMock {
	mock := &ConfigurationProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurationProviderMock is an autogenerated mock type for the ConfigurationProvider type
type ConfigurationProviderMock struct {
	mock.Mock
}

type ConfigurationProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigurationProviderMock) EXPECT() *ConfigurationProviderMock_Expecter {
	return &ConfigurationProviderMock_Expecter{mock: &_m.Mock}
}

// Values provides a mock function for the type ConfigurationProviderMock
func (_mock *ConfigurationProviderMock) Values() (map[string]any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConfigurationProviderMock_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type ConfigurationProviderMock_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *ConfigurationProviderMock_Expecter) Values() *ConfigurationProviderMock_Values_Call {
	return &ConfigurationProviderMock_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *ConfigurationProviderMock_Values_Call) Run(run func()) *ConfigurationProviderMock_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigurationProviderMock_Values_Call) Return(stringToV map[string]any, err error) *ConfigurationProviderMock_Values_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *ConfigurationProviderMock_Values_Call) RunAndReturn(run func() (map[string]any, error)) *ConfigurationProviderMock_Values_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigurableMock creates a new instance of ConfigurableMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurableMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurableMock {
	mock := &ConfigurableMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurableMock is an autogenerated mock type for the Configurable type
type ConfigurableMock struct {
	mock.Mock
}

type ConfigurableMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigurableMock) EXPECT() *ConfigurableMock_Expecter {
	return &ConfigurableMock_Expecter{mock: &_m.Mock}
}

// FromConfiguration provides a mock function for the type ConfigurableMock
func (_mock *ConfigurableMock) FromConfiguration(configuration *contract.Configuration) {
	_mock.Called(configuration)
	return
}

// ConfigurableMock_FromConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromConfiguration'
type ConfigurableMock_FromConfiguration_Call struct {
	*mock.Call
}

// FromConfiguration is a helper method to define mock.On call
//   - configuration *contract.Configuration
func (_e *ConfigurableMock_Expecter) FromConfiguration(configuration any) *ConfigurableMock_FromConfiguration_Call {
	return &ConfigurableMock_FromConfiguration_Call{Call: _e.mock.On("FromConfiguration", configuration)}
}

func (_c *ConfigurableMock_FromConfiguration_Call) Run(run func(configuration *contract.Configuration)) *ConfigurableMock_FromConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *contract.Configuration
		if args[0] != nil {
			arg0 = args[0].(*contract.Configuration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigurableMock_FromConfiguration_Call) Return() *ConfigurableMock_FromConfiguration_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConfigurableMock_FromConfiguration_Call) RunAndReturn(run func(configuration *contract.Configuration)) *ConfigurableMock_FromConfiguration_Call {
	_c.Run(run)
	return _c
}

// NewConfigurablePointerMock creates a new instance of ConfigurablePointerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurablePointerMock[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurablePointerMock[T] {
	mock := &ConfigurablePointerMock[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigurablePointerMock is an autogenerated mock type for the ConfigurablePointer type
type ConfigurablePointerMock[T any] struct {
	mock.Mock
}

type ConfigurablePointerMock_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *ConfigurablePointerMock[T]) EXPECT() *ConfigurablePointerMock_Expecter[T] {
	return &ConfigurablePointerMock_Expecter[T]{mock: &_m.Mock}
}

// FromConfiguration provides a mock function for the type ConfigurablePointerMock
func (_mock *ConfigurablePointerMock[T]) FromConfiguration(configuration *contract.Configuration) {
	_mock.Called(configuration)
	return
}

// ConfigurablePointerMock_FromConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromConfiguration'
type ConfigurablePointerMock_FromConfiguration_Call[T any] struct {
	*mock.Call
}

// FromConfiguration is a helper method to define mock.On call
//   - configuration *contract.Configuration
func (_e *ConfigurablePointerMock_Expecter[T]) FromConfiguration(configuration any) *ConfigurablePointerMock_FromConfiguration_Call[T] {
	return &ConfigurablePointerMock_FromConfiguration_Call[T]{Call: _e.mock.On("FromConfiguration", configuration)}
}

func (_c *ConfigurablePointerMock_FromConfiguration_Call[T]) Run(run func(configuration *contract.Configuration)) *ConfigurablePointerMock_FromConfiguration_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *contract.Configuration
		if args[0] != nil {
			arg0 = args[0].(*contract.Configuration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigurablePointerMock_FromConfiguration_Call[T]) Return() *ConfigurablePointerMock_FromConfiguration_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *ConfigurablePointerMock_FromConfiguration_Call[T]) RunAndReturn(run func(configuration *contract.Configuration)) *ConfigurablePointerMock_FromConfiguration_Call[T] {
	_c.Run(run)
	return _c
}
