// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewEncrypterDriverMock creates a new instance of EncrypterDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncrypterDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncrypterDriverMock {
	mock := &EncrypterDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EncrypterDriverMock is an autogenerated mock type for the EncrypterDriver type
type EncrypterDriverMock struct {
	mock.Mock
}

type EncrypterDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EncrypterDriverMock) EXPECT() *EncrypterDriverMock_Expecter {
	return &EncrypterDriverMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type EncrypterDriverMock
func (_mock *EncrypterDriverMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EncrypterDriverMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type EncrypterDriverMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *EncrypterDriverMock_Expecter) Close() *EncrypterDriverMock_Close_Call {
	return &EncrypterDriverMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *EncrypterDriverMock_Close_Call) Run(run func()) *EncrypterDriverMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EncrypterDriverMock_Close_Call) Return(err error) *EncrypterDriverMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EncrypterDriverMock_Close_Call) RunAndReturn(run func() error) *EncrypterDriverMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function for the type EncrypterDriverMock
func (_mock *EncrypterDriverMock) Decrypt(value []byte) ([]byte, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncrypterDriverMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type EncrypterDriverMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - value []byte
func (_e *EncrypterDriverMock_Expecter) Decrypt(value any) *EncrypterDriverMock_Decrypt_Call {
	return &EncrypterDriverMock_Decrypt_Call{Call: _e.mock.On("Decrypt", value)}
}

func (_c *EncrypterDriverMock_Decrypt_Call) Run(run func(value []byte)) *EncrypterDriverMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncrypterDriverMock_Decrypt_Call) Return(bytes []byte, err error) *EncrypterDriverMock_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EncrypterDriverMock_Decrypt_Call) RunAndReturn(run func(value []byte) ([]byte, error)) *EncrypterDriverMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type EncrypterDriverMock
func (_mock *EncrypterDriverMock) Encrypt(value []byte) ([]byte, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncrypterDriverMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type EncrypterDriverMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - value []byte
func (_e *EncrypterDriverMock_Expecter) Encrypt(value any) *EncrypterDriverMock_Encrypt_Call {
	return &EncrypterDriverMock_Encrypt_Call{Call: _e.mock.On("Encrypt", value)}
}

func (_c *EncrypterDriverMock_Encrypt_Call) Run(run func(value []byte)) *EncrypterDriverMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncrypterDriverMock_Encrypt_Call) Return(bytes []byte, err error) *EncrypterDriverMock_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EncrypterDriverMock_Encrypt_Call) RunAndReturn(run func(value []byte) ([]byte, error)) *EncrypterDriverMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
