// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewDatabaseRowsMock creates a new instance of DatabaseRowsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseRowsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseRowsMock {
	mock := &DatabaseRowsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseRowsMock is an autogenerated mock type for the DatabaseRows type
type DatabaseRowsMock struct {
	mock.Mock
}

type DatabaseRowsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseRowsMock) EXPECT() *DatabaseRowsMock_Expecter {
	return &DatabaseRowsMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DatabaseRowsMock
func (_mock *DatabaseRowsMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRowsMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DatabaseRowsMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DatabaseRowsMock_Expecter) Close() *DatabaseRowsMock_Close_Call {
	return &DatabaseRowsMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DatabaseRowsMock_Close_Call) Run(run func()) *DatabaseRowsMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseRowsMock_Close_Call) Return(err error) *DatabaseRowsMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRowsMock_Close_Call) RunAndReturn(run func() error) *DatabaseRowsMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type DatabaseRowsMock
func (_mock *DatabaseRowsMock) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRowsMock_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type DatabaseRowsMock_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *DatabaseRowsMock_Expecter) Err() *DatabaseRowsMock_Err_Call {
	return &DatabaseRowsMock_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *DatabaseRowsMock_Err_Call) Run(run func()) *DatabaseRowsMock_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseRowsMock_Err_Call) Return(err error) *DatabaseRowsMock_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRowsMock_Err_Call) RunAndReturn(run func() error) *DatabaseRowsMock_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type DatabaseRowsMock
func (_mock *DatabaseRowsMock) Next() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// DatabaseRowsMock_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type DatabaseRowsMock_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *DatabaseRowsMock_Expecter) Next() *DatabaseRowsMock_Next_Call {
	return &DatabaseRowsMock_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *DatabaseRowsMock_Next_Call) Run(run func()) *DatabaseRowsMock_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseRowsMock_Next_Call) Return(b bool) *DatabaseRowsMock_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *DatabaseRowsMock_Next_Call) RunAndReturn(run func() bool) *DatabaseRowsMock_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type DatabaseRowsMock
func (_mock *DatabaseRowsMock) Scan(dest any) error {
	ret := _mock.Called(dest)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseRowsMock_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type DatabaseRowsMock_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest any
func (_e *DatabaseRowsMock_Expecter) Scan(dest any) *DatabaseRowsMock_Scan_Call {
	return &DatabaseRowsMock_Scan_Call{Call: _e.mock.On("Scan", dest)}
}

func (_c *DatabaseRowsMock_Scan_Call) Run(run func(dest any)) *DatabaseRowsMock_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseRowsMock_Scan_Call) Return(err error) *DatabaseRowsMock_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseRowsMock_Scan_Call) RunAndReturn(run func(dest any) error) *DatabaseRowsMock_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewDatabaseDriverMock creates a new instance of DatabaseDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseDriverMock {
	mock := &DatabaseDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseDriverMock is an autogenerated mock type for the DatabaseDriver type
type DatabaseDriverMock struct {
	mock.Mock
}

type DatabaseDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseDriverMock) EXPECT() *DatabaseDriverMock_Expecter {
	return &DatabaseDriverMock_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (int64, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) int64); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseDriverMock_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DatabaseDriverMock_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *DatabaseDriverMock_Expecter) Exec(ctx any, query any, args ...any) *DatabaseDriverMock_Exec_Call {
	return &DatabaseDriverMock_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, query}, args...)...)}
}

func (_c *DatabaseDriverMock_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *DatabaseDriverMock_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_Exec_Call) Return(n int64, err error) *DatabaseDriverMock_Exec_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseDriverMock_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (int64, error)) *DatabaseDriverMock_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecNamed provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) ExecNamed(ctx context.Context, query string, arg any) (int64, error) {
	ret := _mock.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for ExecNamed")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (int64, error)); ok {
		return returnFunc(ctx, query, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) int64); ok {
		r0 = returnFunc(ctx, query, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseDriverMock_ExecNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecNamed'
type DatabaseDriverMock_ExecNamed_Call struct {
	*mock.Call
}

// ExecNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg any
func (_e *DatabaseDriverMock_Expecter) ExecNamed(ctx any, query any, arg any) *DatabaseDriverMock_ExecNamed_Call {
	return &DatabaseDriverMock_ExecNamed_Call{Call: _e.mock.On("ExecNamed", ctx, query, arg)}
}

func (_c *DatabaseDriverMock_ExecNamed_Call) Run(run func(ctx context.Context, query string, arg any)) *DatabaseDriverMock_ExecNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_ExecNamed_Call) Return(n int64, err error) *DatabaseDriverMock_ExecNamed_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseDriverMock_ExecNamed_Call) RunAndReturn(run func(ctx context.Context, query string, arg any) (int64, error)) *DatabaseDriverMock_ExecNamed_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) Find(ctx context.Context, query string, dest any, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, dest, args)
	} else {
		tmpRet = _mock.Called(ctx, query, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...any) error); ok {
		r0 = returnFunc(ctx, query, dest, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseDriverMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type DatabaseDriverMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - args ...any
func (_e *DatabaseDriverMock_Expecter) Find(ctx any, query any, dest any, args ...any) *DatabaseDriverMock_Find_Call {
	return &DatabaseDriverMock_Find_Call{Call: _e.mock.On("Find",
		append([]any{ctx, query, dest}, args...)...)}
}

func (_c *DatabaseDriverMock_Find_Call) Run(run func(ctx context.Context, query string, dest any, args ...any)) *DatabaseDriverMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_Find_Call) Return(err error) *DatabaseDriverMock_Find_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseDriverMock_Find_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, args ...any) error) *DatabaseDriverMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindNamed provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) FindNamed(ctx context.Context, query string, dest any, arg any) error {
	ret := _mock.Called(ctx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNamed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseDriverMock_FindNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNamed'
type DatabaseDriverMock_FindNamed_Call struct {
	*mock.Call
}

// FindNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - arg any
func (_e *DatabaseDriverMock_Expecter) FindNamed(ctx any, query any, dest any, arg any) *DatabaseDriverMock_FindNamed_Call {
	return &DatabaseDriverMock_FindNamed_Call{Call: _e.mock.On("FindNamed", ctx, query, dest, arg)}
}

func (_c *DatabaseDriverMock_FindNamed_Call) Run(run func(ctx context.Context, query string, dest any, arg any)) *DatabaseDriverMock_FindNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_FindNamed_Call) Return(err error) *DatabaseDriverMock_FindNamed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseDriverMock_FindNamed_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, arg any) error) *DatabaseDriverMock_FindNamed_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) Query(ctx context.Context, query string, args ...any) (contract.DatabaseRows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 contract.DatabaseRows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (contract.DatabaseRows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) contract.DatabaseRows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.DatabaseRows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseDriverMock_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DatabaseDriverMock_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *DatabaseDriverMock_Expecter) Query(ctx any, query any, args ...any) *DatabaseDriverMock_Query_Call {
	return &DatabaseDriverMock_Query_Call{Call: _e.mock.On("Query",
		append([]any{ctx, query}, args...)...)}
}

func (_c *DatabaseDriverMock_Query_Call) Run(run func(ctx context.Context, query string, args ...any)) *DatabaseDriverMock_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_Query_Call) Return(databaseRows contract.DatabaseRows, err error) *DatabaseDriverMock_Query_Call {
	_c.Call.Return(databaseRows, err)
	return _c
}

func (_c *DatabaseDriverMock_Query_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (contract.DatabaseRows, error)) *DatabaseDriverMock_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryNamed provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) QueryNamed(ctx context.Context, query string, arg any) (contract.DatabaseRows, error) {
	ret := _mock.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for QueryNamed")
	}

	var r0 contract.DatabaseRows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (contract.DatabaseRows, error)); ok {
		return returnFunc(ctx, query, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) contract.DatabaseRows); ok {
		r0 = returnFunc(ctx, query, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.DatabaseRows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseDriverMock_QueryNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryNamed'
type DatabaseDriverMock_QueryNamed_Call struct {
	*mock.Call
}

// QueryNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg any
func (_e *DatabaseDriverMock_Expecter) QueryNamed(ctx any, query any, arg any) *DatabaseDriverMock_QueryNamed_Call {
	return &DatabaseDriverMock_QueryNamed_Call{Call: _e.mock.On("QueryNamed", ctx, query, arg)}
}

func (_c *DatabaseDriverMock_QueryNamed_Call) Run(run func(ctx context.Context, query string, arg any)) *DatabaseDriverMock_QueryNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_QueryNamed_Call) Return(databaseRows contract.DatabaseRows, err error) *DatabaseDriverMock_QueryNamed_Call {
	_c.Call.Return(databaseRows, err)
	return _c
}

func (_c *DatabaseDriverMock_QueryNamed_Call) RunAndReturn(run func(ctx context.Context, query string, arg any) (contract.DatabaseRows, error)) *DatabaseDriverMock_QueryNamed_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) Select(ctx context.Context, query string, dest any, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, dest, args)
	} else {
		tmpRet = _mock.Called(ctx, query, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...any) error); ok {
		r0 = returnFunc(ctx, query, dest, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseDriverMock_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type DatabaseDriverMock_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - args ...any
func (_e *DatabaseDriverMock_Expecter) Select(ctx any, query any, dest any, args ...any) *DatabaseDriverMock_Select_Call {
	return &DatabaseDriverMock_Select_Call{Call: _e.mock.On("Select",
		append([]any{ctx, query, dest}, args...)...)}
}

func (_c *DatabaseDriverMock_Select_Call) Run(run func(ctx context.Context, query string, dest any, args ...any)) *DatabaseDriverMock_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_Select_Call) Return(err error) *DatabaseDriverMock_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseDriverMock_Select_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, args ...any) error) *DatabaseDriverMock_Select_Call {
	_c.Call.Return(run)
	return _c
}

// SelectNamed provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) SelectNamed(ctx context.Context, query string, dest any, arg any) error {
	ret := _mock.Called(ctx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for SelectNamed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseDriverMock_SelectNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectNamed'
type DatabaseDriverMock_SelectNamed_Call struct {
	*mock.Call
}

// SelectNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - arg any
func (_e *DatabaseDriverMock_Expecter) SelectNamed(ctx any, query any, dest any, arg any) *DatabaseDriverMock_SelectNamed_Call {
	return &DatabaseDriverMock_SelectNamed_Call{Call: _e.mock.On("SelectNamed", ctx, query, dest, arg)}
}

func (_c *DatabaseDriverMock_SelectNamed_Call) Run(run func(ctx context.Context, query string, dest any, arg any)) *DatabaseDriverMock_SelectNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_SelectNamed_Call) Return(err error) *DatabaseDriverMock_SelectNamed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseDriverMock_SelectNamed_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, arg any) error) *DatabaseDriverMock_SelectNamed_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type DatabaseDriverMock
func (_mock *DatabaseDriverMock) WithTransaction(ctx context.Context, fn func(tx contract.DatabaseDriver) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx contract.DatabaseDriver) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseDriverMock_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type DatabaseDriverMock_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx contract.DatabaseDriver) error
func (_e *DatabaseDriverMock_Expecter) WithTransaction(ctx any, fn any) *DatabaseDriverMock_WithTransaction_Call {
	return &DatabaseDriverMock_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *DatabaseDriverMock_WithTransaction_Call) Run(run func(ctx context.Context, fn func(tx contract.DatabaseDriver) error)) *DatabaseDriverMock_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx contract.DatabaseDriver) error
		if args[1] != nil {
			arg1 = args[1].(func(tx contract.DatabaseDriver) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseDriverMock_WithTransaction_Call) Return(err error) *DatabaseDriverMock_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseDriverMock_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx contract.DatabaseDriver) error) error) *DatabaseDriverMock_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
