// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewDatabaseMock creates a new instance of DatabaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseMock {
	mock := &DatabaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatabaseMock is an autogenerated mock type for the Database type
type DatabaseMock struct {
	mock.Mock
}

type DatabaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DatabaseMock) EXPECT() *DatabaseMock_Expecter {
	return &DatabaseMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DatabaseMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DatabaseMock_Expecter) Close() *DatabaseMock_Close_Call {
	return &DatabaseMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DatabaseMock_Close_Call) Run(run func()) *DatabaseMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatabaseMock_Close_Call) Return(err error) *DatabaseMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_Close_Call) RunAndReturn(run func() error) *DatabaseMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) Exec(ctx context.Context, query string, args ...any) (int64, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (int64, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) int64); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseMock_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DatabaseMock_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *DatabaseMock_Expecter) Exec(ctx interface{}, query interface{}, args ...interface{}) *DatabaseMock_Exec_Call {
	return &DatabaseMock_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DatabaseMock_Exec_Call) Run(run func(ctx context.Context, query string, args ...any)) *DatabaseMock_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DatabaseMock_Exec_Call) Return(n int64, err error) *DatabaseMock_Exec_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseMock_Exec_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (int64, error)) *DatabaseMock_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecNamed provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) ExecNamed(ctx context.Context, query string, arg any) (int64, error) {
	ret := _mock.Called(ctx, query, arg)

	if len(ret) == 0 {
		panic("no return value specified for ExecNamed")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) (int64, error)); ok {
		return returnFunc(ctx, query, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) int64); ok {
		r0 = returnFunc(ctx, query, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any) error); ok {
		r1 = returnFunc(ctx, query, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatabaseMock_ExecNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecNamed'
type DatabaseMock_ExecNamed_Call struct {
	*mock.Call
}

// ExecNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - arg any
func (_e *DatabaseMock_Expecter) ExecNamed(ctx interface{}, query interface{}, arg interface{}) *DatabaseMock_ExecNamed_Call {
	return &DatabaseMock_ExecNamed_Call{Call: _e.mock.On("ExecNamed", ctx, query, arg)}
}

func (_c *DatabaseMock_ExecNamed_Call) Run(run func(ctx context.Context, query string, arg any)) *DatabaseMock_ExecNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DatabaseMock_ExecNamed_Call) Return(n int64, err error) *DatabaseMock_ExecNamed_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatabaseMock_ExecNamed_Call) RunAndReturn(run func(ctx context.Context, query string, arg any) (int64, error)) *DatabaseMock_ExecNamed_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) Find(ctx context.Context, query string, dest any, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, dest, args)
	} else {
		tmpRet = _mock.Called(ctx, query, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...any) error); ok {
		r0 = returnFunc(ctx, query, dest, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type DatabaseMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - args ...any
func (_e *DatabaseMock_Expecter) Find(ctx interface{}, query interface{}, dest interface{}, args ...interface{}) *DatabaseMock_Find_Call {
	return &DatabaseMock_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, query, dest}, args...)...)}
}

func (_c *DatabaseMock_Find_Call) Run(run func(ctx context.Context, query string, dest any, args ...any)) *DatabaseMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *DatabaseMock_Find_Call) Return(err error) *DatabaseMock_Find_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_Find_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, args ...any) error) *DatabaseMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindNamed provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) FindNamed(ctx context.Context, query string, dest any, arg any) error {
	ret := _mock.Called(ctx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNamed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_FindNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNamed'
type DatabaseMock_FindNamed_Call struct {
	*mock.Call
}

// FindNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - arg any
func (_e *DatabaseMock_Expecter) FindNamed(ctx interface{}, query interface{}, dest interface{}, arg interface{}) *DatabaseMock_FindNamed_Call {
	return &DatabaseMock_FindNamed_Call{Call: _e.mock.On("FindNamed", ctx, query, dest, arg)}
}

func (_c *DatabaseMock_FindNamed_Call) Run(run func(ctx context.Context, query string, dest any, arg any)) *DatabaseMock_FindNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DatabaseMock_FindNamed_Call) Return(err error) *DatabaseMock_FindNamed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_FindNamed_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, arg any) error) *DatabaseMock_FindNamed_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DatabaseMock_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DatabaseMock_Expecter) Ping(ctx interface{}) *DatabaseMock_Ping_Call {
	return &DatabaseMock_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *DatabaseMock_Ping_Call) Run(run func(ctx context.Context)) *DatabaseMock_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DatabaseMock_Ping_Call) Return(err error) *DatabaseMock_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *DatabaseMock_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) Select(ctx context.Context, query string, dest any, args ...any) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, dest, args)
	} else {
		tmpRet = _mock.Called(ctx, query, dest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...any) error); ok {
		r0 = returnFunc(ctx, query, dest, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type DatabaseMock_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - args ...any
func (_e *DatabaseMock_Expecter) Select(ctx interface{}, query interface{}, dest interface{}, args ...interface{}) *DatabaseMock_Select_Call {
	return &DatabaseMock_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, query, dest}, args...)...)}
}

func (_c *DatabaseMock_Select_Call) Run(run func(ctx context.Context, query string, dest any, args ...any)) *DatabaseMock_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *DatabaseMock_Select_Call) Return(err error) *DatabaseMock_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_Select_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, args ...any) error) *DatabaseMock_Select_Call {
	_c.Call.Return(run)
	return _c
}

// SelectNamed provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) SelectNamed(ctx context.Context, query string, dest any, arg any) error {
	ret := _mock.Called(ctx, query, dest, arg)

	if len(ret) == 0 {
		panic("no return value specified for SelectNamed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, query, dest, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_SelectNamed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectNamed'
type DatabaseMock_SelectNamed_Call struct {
	*mock.Call
}

// SelectNamed is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - dest any
//   - arg any
func (_e *DatabaseMock_Expecter) SelectNamed(ctx interface{}, query interface{}, dest interface{}, arg interface{}) *DatabaseMock_SelectNamed_Call {
	return &DatabaseMock_SelectNamed_Call{Call: _e.mock.On("SelectNamed", ctx, query, dest, arg)}
}

func (_c *DatabaseMock_SelectNamed_Call) Run(run func(ctx context.Context, query string, dest any, arg any)) *DatabaseMock_SelectNamed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DatabaseMock_SelectNamed_Call) Return(err error) *DatabaseMock_SelectNamed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_SelectNamed_Call) RunAndReturn(run func(ctx context.Context, query string, dest any, arg any) error) *DatabaseMock_SelectNamed_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type DatabaseMock
func (_mock *DatabaseMock) WithTransaction(ctx context.Context, fn func(tx contract.Database) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx contract.Database) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatabaseMock_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type DatabaseMock_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx contract.Database) error
func (_e *DatabaseMock_Expecter) WithTransaction(ctx interface{}, fn interface{}) *DatabaseMock_WithTransaction_Call {
	return &DatabaseMock_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *DatabaseMock_WithTransaction_Call) Run(run func(ctx context.Context, fn func(tx contract.Database) error)) *DatabaseMock_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx contract.Database) error
		if args[1] != nil {
			arg1 = args[1].(func(tx contract.Database) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatabaseMock_WithTransaction_Call) Return(err error) *DatabaseMock_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatabaseMock_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx contract.Database) error) error) *DatabaseMock_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
