// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewEventPublisherDriverMock creates a new instance of EventPublisherDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisherDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisherDriverMock {
	mock := &EventPublisherDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventPublisherDriverMock is an autogenerated mock type for the EventPublisherDriver type
type EventPublisherDriverMock struct {
	mock.Mock
}

type EventPublisherDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisherDriverMock) EXPECT() *EventPublisherDriverMock_Expecter {
	return &EventPublisherDriverMock_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type EventPublisherDriverMock
func (_mock *EventPublisherDriverMock) Publish(ctx context.Context, event string, payload []byte) error {
	ret := _mock.Called(ctx, event, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, event, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisherDriverMock_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventPublisherDriverMock_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - payload []byte
func (_e *EventPublisherDriverMock_Expecter) Publish(ctx any, event any, payload any) *EventPublisherDriverMock_Publish_Call {
	return &EventPublisherDriverMock_Publish_Call{Call: _e.mock.On("Publish", ctx, event, payload)}
}

func (_c *EventPublisherDriverMock_Publish_Call) Run(run func(ctx context.Context, event string, payload []byte)) *EventPublisherDriverMock_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventPublisherDriverMock_Publish_Call) Return(err error) *EventPublisherDriverMock_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisherDriverMock_Publish_Call) RunAndReturn(run func(ctx context.Context, event string, payload []byte) error) *EventPublisherDriverMock_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventSubscriberDriverMock creates a new instance of EventSubscriberDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSubscriberDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSubscriberDriverMock {
	mock := &EventSubscriberDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventSubscriberDriverMock is an autogenerated mock type for the EventSubscriberDriver type
type EventSubscriberDriverMock struct {
	mock.Mock
}

type EventSubscriberDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventSubscriberDriverMock) EXPECT() *EventSubscriberDriverMock_Expecter {
	return &EventSubscriberDriverMock_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type EventSubscriberDriverMock
func (_mock *EventSubscriberDriverMock) Subscribe(ctx context.Context, event string, handler contract.EventHandler) (contract.EventUnsubscribeFunc, error) {
	ret := _mock.Called(ctx, event, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 contract.EventUnsubscribeFunc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, contract.EventHandler) (contract.EventUnsubscribeFunc, error)); ok {
		return returnFunc(ctx, event, handler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, contract.EventHandler) contract.EventUnsubscribeFunc); ok {
		r0 = returnFunc(ctx, event, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.EventUnsubscribeFunc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, contract.EventHandler) error); ok {
		r1 = returnFunc(ctx, event, handler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventSubscriberDriverMock_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventSubscriberDriverMock_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - handler contract.EventHandler
func (_e *EventSubscriberDriverMock_Expecter) Subscribe(ctx any, event any, handler any) *EventSubscriberDriverMock_Subscribe_Call {
	return &EventSubscriberDriverMock_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, event, handler)}
}

func (_c *EventSubscriberDriverMock_Subscribe_Call) Run(run func(ctx context.Context, event string, handler contract.EventHandler)) *EventSubscriberDriverMock_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 contract.EventHandler
		if args[2] != nil {
			arg2 = args[2].(contract.EventHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventSubscriberDriverMock_Subscribe_Call) Return(v contract.EventUnsubscribeFunc, err error) *EventSubscriberDriverMock_Subscribe_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EventSubscriberDriverMock_Subscribe_Call) RunAndReturn(run func(ctx context.Context, event string, handler contract.EventHandler) (contract.EventUnsubscribeFunc, error)) *EventSubscriberDriverMock_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
