// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewEventsMock creates a new instance of EventsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsMock {
	mock := &EventsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventsMock is an autogenerated mock type for the Events type
type EventsMock struct {
	mock.Mock
}

type EventsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventsMock) EXPECT() *EventsMock_Expecter {
	return &EventsMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type EventsMock
func (_mock *EventsMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventsMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type EventsMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *EventsMock_Expecter) Close() *EventsMock_Close_Call {
	return &EventsMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *EventsMock_Close_Call) Run(run func()) *EventsMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventsMock_Close_Call) Return(err error) *EventsMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventsMock_Close_Call) RunAndReturn(run func() error) *EventsMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type EventsMock
func (_mock *EventsMock) Publish(ctx context.Context, event string, payload any) error {
	ret := _mock.Called(ctx, event, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, event, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventsMock_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventsMock_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - payload any
func (_e *EventsMock_Expecter) Publish(ctx interface{}, event interface{}, payload interface{}) *EventsMock_Publish_Call {
	return &EventsMock_Publish_Call{Call: _e.mock.On("Publish", ctx, event, payload)}
}

func (_c *EventsMock_Publish_Call) Run(run func(ctx context.Context, event string, payload any)) *EventsMock_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventsMock_Publish_Call) Return(err error) *EventsMock_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventsMock_Publish_Call) RunAndReturn(run func(ctx context.Context, event string, payload any) error) *EventsMock_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type EventsMock
func (_mock *EventsMock) Subscribe(ctx context.Context, event string, handler contract.EventHandler) (contract.EventUnsubscribeFunc, error) {
	ret := _mock.Called(ctx, event, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 contract.EventUnsubscribeFunc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, contract.EventHandler) (contract.EventUnsubscribeFunc, error)); ok {
		return returnFunc(ctx, event, handler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, contract.EventHandler) contract.EventUnsubscribeFunc); ok {
		r0 = returnFunc(ctx, event, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.EventUnsubscribeFunc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, contract.EventHandler) error); ok {
		r1 = returnFunc(ctx, event, handler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EventsMock_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventsMock_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - event string
//   - handler contract.EventHandler
func (_e *EventsMock_Expecter) Subscribe(ctx interface{}, event interface{}, handler interface{}) *EventsMock_Subscribe_Call {
	return &EventsMock_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, event, handler)}
}

func (_c *EventsMock_Subscribe_Call) Run(run func(ctx context.Context, event string, handler contract.EventHandler)) *EventsMock_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 contract.EventHandler
		if args[2] != nil {
			arg2 = args[2].(contract.EventHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventsMock_Subscribe_Call) Return(v contract.EventUnsubscribeFunc, err error) *EventsMock_Subscribe_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *EventsMock_Subscribe_Call) RunAndReturn(run func(ctx context.Context, event string, handler contract.EventHandler) (contract.EventUnsubscribeFunc, error)) *EventsMock_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
