// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHasherMock creates a new instance of HasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasherMock {
	mock := &HasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HasherMock is an autogenerated mock type for the Hasher type
type HasherMock struct {
	mock.Mock
}

type HasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HasherMock) EXPECT() *HasherMock_Expecter {
	return &HasherMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type HasherMock
func (_mock *HasherMock) Check(value []byte, hash []byte) (bool, error) {
	ret := _mock.Called(value, hash)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) (bool, error)); ok {
		return returnFunc(value, hash)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) bool); ok {
		r0 = returnFunc(value, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(value, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasherMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HasherMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - value []byte
//   - hash []byte
func (_e *HasherMock_Expecter) Check(value interface{}, hash interface{}) *HasherMock_Check_Call {
	return &HasherMock_Check_Call{Call: _e.mock.On("Check", value, hash)}
}

func (_c *HasherMock_Check_Call) Run(run func(value []byte, hash []byte)) *HasherMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HasherMock_Check_Call) Return(b bool, err error) *HasherMock_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *HasherMock_Check_Call) RunAndReturn(run func(value []byte, hash []byte) (bool, error)) *HasherMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type HasherMock
func (_mock *HasherMock) Hash(value []byte) ([]byte, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasherMock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HasherMock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - value []byte
func (_e *HasherMock_Expecter) Hash(value interface{}) *HasherMock_Hash_Call {
	return &HasherMock_Hash_Call{Call: _e.mock.On("Hash", value)}
}

func (_c *HasherMock_Hash_Call) Run(run func(value []byte)) *HasherMock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HasherMock_Hash_Call) Return(bytes []byte, err error) *HasherMock_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *HasherMock_Hash_Call) RunAndReturn(run func(value []byte) ([]byte, error)) *HasherMock_Hash_Call {
	_c.Call.Return(run)
	return _c
}
