// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHasherDriverMock creates a new instance of HasherDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasherDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasherDriverMock {
	mock := &HasherDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HasherDriverMock is an autogenerated mock type for the HasherDriver type
type HasherDriverMock struct {
	mock.Mock
}

type HasherDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HasherDriverMock) EXPECT() *HasherDriverMock_Expecter {
	return &HasherDriverMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type HasherDriverMock
func (_mock *HasherDriverMock) Check(value []byte, hash []byte) (bool, error) {
	ret := _mock.Called(value, hash)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) (bool, error)); ok {
		return returnFunc(value, hash)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) bool); ok {
		r0 = returnFunc(value, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(value, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasherDriverMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HasherDriverMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - value []byte
//   - hash []byte
func (_e *HasherDriverMock_Expecter) Check(value any, hash any) *HasherDriverMock_Check_Call {
	return &HasherDriverMock_Check_Call{Call: _e.mock.On("Check", value, hash)}
}

func (_c *HasherDriverMock_Check_Call) Run(run func(value []byte, hash []byte)) *HasherDriverMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HasherDriverMock_Check_Call) Return(b bool, err error) *HasherDriverMock_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *HasherDriverMock_Check_Call) RunAndReturn(run func(value []byte, hash []byte) (bool, error)) *HasherDriverMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type HasherDriverMock
func (_mock *HasherDriverMock) Hash(value []byte) ([]byte, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasherDriverMock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HasherDriverMock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - value []byte
func (_e *HasherDriverMock_Expecter) Hash(value any) *HasherDriverMock_Hash_Call {
	return &HasherDriverMock_Hash_Call{Call: _e.mock.On("Hash", value)}
}

func (_c *HasherDriverMock_Hash_Call) Run(run func(value []byte)) *HasherDriverMock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HasherDriverMock_Hash_Call) Return(bytes []byte, err error) *HasherDriverMock_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *HasherDriverMock_Hash_Call) RunAndReturn(run func(value []byte) ([]byte, error)) *HasherDriverMock_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewRehashableMock creates a new instance of RehashableMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRehashableMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RehashableMock {
	mock := &RehashableMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RehashableMock is an autogenerated mock type for the Rehashable type
type RehashableMock struct {
	mock.Mock
}

type RehashableMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RehashableMock) EXPECT() *RehashableMock_Expecter {
	return &RehashableMock_Expecter{mock: &_m.Mock}
}

// NeedsRehash provides a mock function for the type RehashableMock
func (_mock *RehashableMock) NeedsRehash(hash []byte) bool {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for NeedsRehash")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RehashableMock_NeedsRehash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NeedsRehash'
type RehashableMock_NeedsRehash_Call struct {
	*mock.Call
}

// NeedsRehash is a helper method to define mock.On call
//   - hash []byte
func (_e *RehashableMock_Expecter) NeedsRehash(hash any) *RehashableMock_NeedsRehash_Call {
	return &RehashableMock_NeedsRehash_Call{Call: _e.mock.On("NeedsRehash", hash)}
}

func (_c *RehashableMock_NeedsRehash_Call) Run(run func(hash []byte)) *RehashableMock_NeedsRehash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RehashableMock_NeedsRehash_Call) Return(b bool) *RehashableMock_NeedsRehash_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RehashableMock_NeedsRehash_Call) RunAndReturn(run func(hash []byte) bool) *RehashableMock_NeedsRehash_Call {
	_c.Call.Return(run)
	return _c
}
