// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewHooksMock creates a new instance of HooksMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHooksMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HooksMock {
	mock := &HooksMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HooksMock is an autogenerated mock type for the Hooks type
type HooksMock struct {
	mock.Mock
}

type HooksMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HooksMock) EXPECT() *HooksMock_Expecter {
	return &HooksMock_Expecter{mock: &_m.Mock}
}

// AfterResponse provides a mock function for the type HooksMock
func (_mock *HooksMock) AfterResponse(callbacks ...contract.AfterResponseHook) {
	if len(callbacks) > 0 {
		_mock.Called(callbacks)
	} else {
		_mock.Called()
	}

	return
}

// HooksMock_AfterResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AfterResponse'
type HooksMock_AfterResponse_Call struct {
	*mock.Call
}

// AfterResponse is a helper method to define mock.On call
//   - callbacks ...contract.AfterResponseHook
func (_e *HooksMock_Expecter) AfterResponse(callbacks ...any) *HooksMock_AfterResponse_Call {
	return &HooksMock_AfterResponse_Call{Call: _e.mock.On("AfterResponse",
		append([]any{}, callbacks...)...)}
}

func (_c *HooksMock_AfterResponse_Call) Run(run func(callbacks ...contract.AfterResponseHook)) *HooksMock_AfterResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []contract.AfterResponseHook
		var variadicArgs []contract.AfterResponseHook
		if len(args) > 0 {
			variadicArgs = args[0].([]contract.AfterResponseHook)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *HooksMock_AfterResponse_Call) Return() *HooksMock_AfterResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *HooksMock_AfterResponse_Call) RunAndReturn(run func(callbacks ...contract.AfterResponseHook)) *HooksMock_AfterResponse_Call {
	_c.Run(run)
	return _c
}

// AfterResponseFuncs provides a mock function for the type HooksMock
func (_mock *HooksMock) AfterResponseFuncs() []contract.AfterResponseHook {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AfterResponseFuncs")
	}

	var r0 []contract.AfterResponseHook
	if returnFunc, ok := ret.Get(0).(func() []contract.AfterResponseHook); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.AfterResponseHook)
		}
	}
	return r0
}

// HooksMock_AfterResponseFuncs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AfterResponseFuncs'
type HooksMock_AfterResponseFuncs_Call struct {
	*mock.Call
}

// AfterResponseFuncs is a helper method to define mock.On call
func (_e *HooksMock_Expecter) AfterResponseFuncs() *HooksMock_AfterResponseFuncs_Call {
	return &HooksMock_AfterResponseFuncs_Call{Call: _e.mock.On("AfterResponseFuncs")}
}

func (_c *HooksMock_AfterResponseFuncs_Call) Run(run func()) *HooksMock_AfterResponseFuncs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HooksMock_AfterResponseFuncs_Call) Return(vs []contract.AfterResponseHook) *HooksMock_AfterResponseFuncs_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *HooksMock_AfterResponseFuncs_Call) RunAndReturn(run func() []contract.AfterResponseHook) *HooksMock_AfterResponseFuncs_Call {
	_c.Call.Return(run)
	return _c
}

// BeforeWrite provides a mock function for the type HooksMock
func (_mock *HooksMock) BeforeWrite(callbacks ...contract.BeforeWriteHook) {
	if len(callbacks) > 0 {
		_mock.Called(callbacks)
	} else {
		_mock.Called()
	}

	return
}

// HooksMock_BeforeWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeWrite'
type HooksMock_BeforeWrite_Call struct {
	*mock.Call
}

// BeforeWrite is a helper method to define mock.On call
//   - callbacks ...contract.BeforeWriteHook
func (_e *HooksMock_Expecter) BeforeWrite(callbacks ...any) *HooksMock_BeforeWrite_Call {
	return &HooksMock_BeforeWrite_Call{Call: _e.mock.On("BeforeWrite",
		append([]any{}, callbacks...)...)}
}

func (_c *HooksMock_BeforeWrite_Call) Run(run func(callbacks ...contract.BeforeWriteHook)) *HooksMock_BeforeWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []contract.BeforeWriteHook
		var variadicArgs []contract.BeforeWriteHook
		if len(args) > 0 {
			variadicArgs = args[0].([]contract.BeforeWriteHook)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *HooksMock_BeforeWrite_Call) Return() *HooksMock_BeforeWrite_Call {
	_c.Call.Return()
	return _c
}

func (_c *HooksMock_BeforeWrite_Call) RunAndReturn(run func(callbacks ...contract.BeforeWriteHook)) *HooksMock_BeforeWrite_Call {
	_c.Run(run)
	return _c
}

// BeforeWriteFuncs provides a mock function for the type HooksMock
func (_mock *HooksMock) BeforeWriteFuncs() []contract.BeforeWriteHook {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeforeWriteFuncs")
	}

	var r0 []contract.BeforeWriteHook
	if returnFunc, ok := ret.Get(0).(func() []contract.BeforeWriteHook); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.BeforeWriteHook)
		}
	}
	return r0
}

// HooksMock_BeforeWriteFuncs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeWriteFuncs'
type HooksMock_BeforeWriteFuncs_Call struct {
	*mock.Call
}

// BeforeWriteFuncs is a helper method to define mock.On call
func (_e *HooksMock_Expecter) BeforeWriteFuncs() *HooksMock_BeforeWriteFuncs_Call {
	return &HooksMock_BeforeWriteFuncs_Call{Call: _e.mock.On("BeforeWriteFuncs")}
}

func (_c *HooksMock_BeforeWriteFuncs_Call) Run(run func()) *HooksMock_BeforeWriteFuncs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HooksMock_BeforeWriteFuncs_Call) Return(vs []contract.BeforeWriteHook) *HooksMock_BeforeWriteFuncs_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *HooksMock_BeforeWriteFuncs_Call) RunAndReturn(run func() []contract.BeforeWriteHook) *HooksMock_BeforeWriteFuncs_Call {
	_c.Call.Return(run)
	return _c
}

// BeforeWriteHeader provides a mock function for the type HooksMock
func (_mock *HooksMock) BeforeWriteHeader(callbacks ...contract.BeforeWriteHeaderHook) {
	if len(callbacks) > 0 {
		_mock.Called(callbacks)
	} else {
		_mock.Called()
	}

	return
}

// HooksMock_BeforeWriteHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeWriteHeader'
type HooksMock_BeforeWriteHeader_Call struct {
	*mock.Call
}

// BeforeWriteHeader is a helper method to define mock.On call
//   - callbacks ...contract.BeforeWriteHeaderHook
func (_e *HooksMock_Expecter) BeforeWriteHeader(callbacks ...any) *HooksMock_BeforeWriteHeader_Call {
	return &HooksMock_BeforeWriteHeader_Call{Call: _e.mock.On("BeforeWriteHeader",
		append([]any{}, callbacks...)...)}
}

func (_c *HooksMock_BeforeWriteHeader_Call) Run(run func(callbacks ...contract.BeforeWriteHeaderHook)) *HooksMock_BeforeWriteHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []contract.BeforeWriteHeaderHook
		var variadicArgs []contract.BeforeWriteHeaderHook
		if len(args) > 0 {
			variadicArgs = args[0].([]contract.BeforeWriteHeaderHook)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *HooksMock_BeforeWriteHeader_Call) Return() *HooksMock_BeforeWriteHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *HooksMock_BeforeWriteHeader_Call) RunAndReturn(run func(callbacks ...contract.BeforeWriteHeaderHook)) *HooksMock_BeforeWriteHeader_Call {
	_c.Run(run)
	return _c
}

// BeforeWriteHeaderFuncs provides a mock function for the type HooksMock
func (_mock *HooksMock) BeforeWriteHeaderFuncs() []contract.BeforeWriteHeaderHook {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeforeWriteHeaderFuncs")
	}

	var r0 []contract.BeforeWriteHeaderHook
	if returnFunc, ok := ret.Get(0).(func() []contract.BeforeWriteHeaderHook); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contract.BeforeWriteHeaderHook)
		}
	}
	return r0
}

// HooksMock_BeforeWriteHeaderFuncs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeWriteHeaderFuncs'
type HooksMock_BeforeWriteHeaderFuncs_Call struct {
	*mock.Call
}

// BeforeWriteHeaderFuncs is a helper method to define mock.On call
func (_e *HooksMock_Expecter) BeforeWriteHeaderFuncs() *HooksMock_BeforeWriteHeaderFuncs_Call {
	return &HooksMock_BeforeWriteHeaderFuncs_Call{Call: _e.mock.On("BeforeWriteHeaderFuncs")}
}

func (_c *HooksMock_BeforeWriteHeaderFuncs_Call) Run(run func()) *HooksMock_BeforeWriteHeaderFuncs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HooksMock_BeforeWriteHeaderFuncs_Call) Return(vs []contract.BeforeWriteHeaderHook) *HooksMock_BeforeWriteHeaderFuncs_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *HooksMock_BeforeWriteHeaderFuncs_Call) RunAndReturn(run func() []contract.BeforeWriteHeaderHook) *HooksMock_BeforeWriteHeaderFuncs_Call {
	_c.Call.Return(run)
	return _c
}
