// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
	"time"
)

// NewJobMock creates a new instance of JobMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobMock {
	mock := &JobMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobMock is an autogenerated mock type for the Job type
type JobMock struct {
	mock.Mock
}

type JobMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobMock) EXPECT() *JobMock_Expecter {
	return &JobMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type JobMock
func (_mock *JobMock) Handle(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type JobMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobMock_Expecter) Handle(ctx any) *JobMock_Handle_Call {
	return &JobMock_Handle_Call{Call: _e.mock.On("Handle", ctx)}
}

func (_c *JobMock_Handle_Call) Run(run func(ctx context.Context)) *JobMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobMock_Handle_Call) Return(err error) *JobMock_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobMock_Handle_Call) RunAndReturn(run func(ctx context.Context) error) *JobMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type JobMock
func (_mock *JobMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// JobMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type JobMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *JobMock_Expecter) Name() *JobMock_Name_Call {
	return &JobMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *JobMock_Name_Call) Run(run func()) *JobMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobMock_Name_Call) Return(s string) *JobMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *JobMock_Name_Call) RunAndReturn(run func() string) *JobMock_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Queue provides a mock function for the type JobMock
func (_mock *JobMock) Queue() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Queue")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// JobMock_Queue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queue'
type JobMock_Queue_Call struct {
	*mock.Call
}

// Queue is a helper method to define mock.On call
func (_e *JobMock_Expecter) Queue() *JobMock_Queue_Call {
	return &JobMock_Queue_Call{Call: _e.mock.On("Queue")}
}

func (_c *JobMock_Queue_Call) Run(run func()) *JobMock_Queue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobMock_Queue_Call) Return(s string) *JobMock_Queue_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *JobMock_Queue_Call) RunAndReturn(run func() string) *JobMock_Queue_Call {
	_c.Call.Return(run)
	return _c
}

// RetryPolicy provides a mock function for the type JobMock
func (_mock *JobMock) RetryPolicy() contract.RetryPolicy {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RetryPolicy")
	}

	var r0 contract.RetryPolicy
	if returnFunc, ok := ret.Get(0).(func() contract.RetryPolicy); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(contract.RetryPolicy)
	}
	return r0
}

// JobMock_RetryPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryPolicy'
type JobMock_RetryPolicy_Call struct {
	*mock.Call
}

// RetryPolicy is a helper method to define mock.On call
func (_e *JobMock_Expecter) RetryPolicy() *JobMock_RetryPolicy_Call {
	return &JobMock_RetryPolicy_Call{Call: _e.mock.On("RetryPolicy")}
}

func (_c *JobMock_RetryPolicy_Call) Run(run func()) *JobMock_RetryPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobMock_RetryPolicy_Call) Return(retryPolicy contract.RetryPolicy) *JobMock_RetryPolicy_Call {
	_c.Call.Return(retryPolicy)
	return _c
}

func (_c *JobMock_RetryPolicy_Call) RunAndReturn(run func() contract.RetryPolicy) *JobMock_RetryPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobDispatcherDriverMock creates a new instance of JobDispatcherDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobDispatcherDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobDispatcherDriverMock {
	mock := &JobDispatcherDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobDispatcherDriverMock is an autogenerated mock type for the JobDispatcherDriver type
type JobDispatcherDriverMock struct {
	mock.Mock
}

type JobDispatcherDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobDispatcherDriverMock) EXPECT() *JobDispatcherDriverMock_Expecter {
	return &JobDispatcherDriverMock_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type JobDispatcherDriverMock
func (_mock *JobDispatcherDriverMock) Dispatch(ctx context.Context, message contract.JobMessage) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, contract.JobMessage) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobDispatcherDriverMock_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type JobDispatcherDriverMock_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - message contract.JobMessage
func (_e *JobDispatcherDriverMock_Expecter) Dispatch(ctx any, message any) *JobDispatcherDriverMock_Dispatch_Call {
	return &JobDispatcherDriverMock_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, message)}
}

func (_c *JobDispatcherDriverMock_Dispatch_Call) Run(run func(ctx context.Context, message contract.JobMessage)) *JobDispatcherDriverMock_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 contract.JobMessage
		if args[1] != nil {
			arg1 = args[1].(contract.JobMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobDispatcherDriverMock_Dispatch_Call) Return(err error) *JobDispatcherDriverMock_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobDispatcherDriverMock_Dispatch_Call) RunAndReturn(run func(ctx context.Context, message contract.JobMessage) error) *JobDispatcherDriverMock_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobSettlementErrorMock creates a new instance of JobSettlementErrorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobSettlementErrorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobSettlementErrorMock {
	mock := &JobSettlementErrorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobSettlementErrorMock is an autogenerated mock type for the JobSettlementError type
type JobSettlementErrorMock struct {
	mock.Mock
}

type JobSettlementErrorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobSettlementErrorMock) EXPECT() *JobSettlementErrorMock_Expecter {
	return &JobSettlementErrorMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type JobSettlementErrorMock
func (_mock *JobSettlementErrorMock) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// JobSettlementErrorMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type JobSettlementErrorMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *JobSettlementErrorMock_Expecter) Error() *JobSettlementErrorMock_Error_Call {
	return &JobSettlementErrorMock_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *JobSettlementErrorMock_Error_Call) Run(run func()) *JobSettlementErrorMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobSettlementErrorMock_Error_Call) Return(s string) *JobSettlementErrorMock_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *JobSettlementErrorMock_Error_Call) RunAndReturn(run func() string) *JobSettlementErrorMock_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Settlement provides a mock function for the type JobSettlementErrorMock
func (_mock *JobSettlementErrorMock) Settlement() contract.JobSettlement {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Settlement")
	}

	var r0 contract.JobSettlement
	if returnFunc, ok := ret.Get(0).(func() contract.JobSettlement); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(contract.JobSettlement)
	}
	return r0
}

// JobSettlementErrorMock_Settlement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Settlement'
type JobSettlementErrorMock_Settlement_Call struct {
	*mock.Call
}

// Settlement is a helper method to define mock.On call
func (_e *JobSettlementErrorMock_Expecter) Settlement() *JobSettlementErrorMock_Settlement_Call {
	return &JobSettlementErrorMock_Settlement_Call{Call: _e.mock.On("Settlement")}
}

func (_c *JobSettlementErrorMock_Settlement_Call) Run(run func()) *JobSettlementErrorMock_Settlement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobSettlementErrorMock_Settlement_Call) Return(jobSettlement contract.JobSettlement) *JobSettlementErrorMock_Settlement_Call {
	_c.Call.Return(jobSettlement)
	return _c
}

func (_c *JobSettlementErrorMock_Settlement_Call) RunAndReturn(run func() contract.JobSettlement) *JobSettlementErrorMock_Settlement_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type JobSettlementErrorMock
func (_mock *JobSettlementErrorMock) Unwrap() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobSettlementErrorMock_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type JobSettlementErrorMock_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *JobSettlementErrorMock_Expecter) Unwrap() *JobSettlementErrorMock_Unwrap_Call {
	return &JobSettlementErrorMock_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *JobSettlementErrorMock_Unwrap_Call) Run(run func()) *JobSettlementErrorMock_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobSettlementErrorMock_Unwrap_Call) Return(err error) *JobSettlementErrorMock_Unwrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobSettlementErrorMock_Unwrap_Call) RunAndReturn(run func() error) *JobSettlementErrorMock_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobRetryAfterErrorMock creates a new instance of JobRetryAfterErrorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRetryAfterErrorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRetryAfterErrorMock {
	mock := &JobRetryAfterErrorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobRetryAfterErrorMock is an autogenerated mock type for the JobRetryAfterError type
type JobRetryAfterErrorMock struct {
	mock.Mock
}

type JobRetryAfterErrorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobRetryAfterErrorMock) EXPECT() *JobRetryAfterErrorMock_Expecter {
	return &JobRetryAfterErrorMock_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type JobRetryAfterErrorMock
func (_mock *JobRetryAfterErrorMock) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// JobRetryAfterErrorMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type JobRetryAfterErrorMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *JobRetryAfterErrorMock_Expecter) Error() *JobRetryAfterErrorMock_Error_Call {
	return &JobRetryAfterErrorMock_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *JobRetryAfterErrorMock_Error_Call) Run(run func()) *JobRetryAfterErrorMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobRetryAfterErrorMock_Error_Call) Return(s string) *JobRetryAfterErrorMock_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *JobRetryAfterErrorMock_Error_Call) RunAndReturn(run func() string) *JobRetryAfterErrorMock_Error_Call {
	_c.Call.Return(run)
	return _c
}

// RetryAfter provides a mock function for the type JobRetryAfterErrorMock
func (_mock *JobRetryAfterErrorMock) RetryAfter() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RetryAfter")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// JobRetryAfterErrorMock_RetryAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryAfter'
type JobRetryAfterErrorMock_RetryAfter_Call struct {
	*mock.Call
}

// RetryAfter is a helper method to define mock.On call
func (_e *JobRetryAfterErrorMock_Expecter) RetryAfter() *JobRetryAfterErrorMock_RetryAfter_Call {
	return &JobRetryAfterErrorMock_RetryAfter_Call{Call: _e.mock.On("RetryAfter")}
}

func (_c *JobRetryAfterErrorMock_RetryAfter_Call) Run(run func()) *JobRetryAfterErrorMock_RetryAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobRetryAfterErrorMock_RetryAfter_Call) Return(duration time.Duration) *JobRetryAfterErrorMock_RetryAfter_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *JobRetryAfterErrorMock_RetryAfter_Call) RunAndReturn(run func() time.Duration) *JobRetryAfterErrorMock_RetryAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Settlement provides a mock function for the type JobRetryAfterErrorMock
func (_mock *JobRetryAfterErrorMock) Settlement() contract.JobSettlement {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Settlement")
	}

	var r0 contract.JobSettlement
	if returnFunc, ok := ret.Get(0).(func() contract.JobSettlement); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(contract.JobSettlement)
	}
	return r0
}

// JobRetryAfterErrorMock_Settlement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Settlement'
type JobRetryAfterErrorMock_Settlement_Call struct {
	*mock.Call
}

// Settlement is a helper method to define mock.On call
func (_e *JobRetryAfterErrorMock_Expecter) Settlement() *JobRetryAfterErrorMock_Settlement_Call {
	return &JobRetryAfterErrorMock_Settlement_Call{Call: _e.mock.On("Settlement")}
}

func (_c *JobRetryAfterErrorMock_Settlement_Call) Run(run func()) *JobRetryAfterErrorMock_Settlement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobRetryAfterErrorMock_Settlement_Call) Return(jobSettlement contract.JobSettlement) *JobRetryAfterErrorMock_Settlement_Call {
	_c.Call.Return(jobSettlement)
	return _c
}

func (_c *JobRetryAfterErrorMock_Settlement_Call) RunAndReturn(run func() contract.JobSettlement) *JobRetryAfterErrorMock_Settlement_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type JobRetryAfterErrorMock
func (_mock *JobRetryAfterErrorMock) Unwrap() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobRetryAfterErrorMock_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type JobRetryAfterErrorMock_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *JobRetryAfterErrorMock_Expecter) Unwrap() *JobRetryAfterErrorMock_Unwrap_Call {
	return &JobRetryAfterErrorMock_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *JobRetryAfterErrorMock_Unwrap_Call) Run(run func()) *JobRetryAfterErrorMock_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobRetryAfterErrorMock_Unwrap_Call) Return(err error) *JobRetryAfterErrorMock_Unwrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobRetryAfterErrorMock_Unwrap_Call) RunAndReturn(run func() error) *JobRetryAfterErrorMock_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobResolverMock creates a new instance of JobResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobResolverMock {
	mock := &JobResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobResolverMock is an autogenerated mock type for the JobResolver type
type JobResolverMock struct {
	mock.Mock
}

type JobResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobResolverMock) EXPECT() *JobResolverMock_Expecter {
	return &JobResolverMock_Expecter{mock: &_m.Mock}
}

// ResolveJob provides a mock function for the type JobResolverMock
func (_mock *JobResolverMock) ResolveJob(name string) (contract.Job, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveJob")
	}

	var r0 contract.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (contract.Job, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) contract.Job); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobResolverMock_ResolveJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveJob'
type JobResolverMock_ResolveJob_Call struct {
	*mock.Call
}

// ResolveJob is a helper method to define mock.On call
//   - name string
func (_e *JobResolverMock_Expecter) ResolveJob(name any) *JobResolverMock_ResolveJob_Call {
	return &JobResolverMock_ResolveJob_Call{Call: _e.mock.On("ResolveJob", name)}
}

func (_c *JobResolverMock_ResolveJob_Call) Run(run func(name string)) *JobResolverMock_ResolveJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobResolverMock_ResolveJob_Call) Return(job contract.Job, err error) *JobResolverMock_ResolveJob_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobResolverMock_ResolveJob_Call) RunAndReturn(run func(name string) (contract.Job, error)) *JobResolverMock_ResolveJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobDeliveryMock creates a new instance of JobDeliveryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobDeliveryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobDeliveryMock {
	mock := &JobDeliveryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobDeliveryMock is an autogenerated mock type for the JobDelivery type
type JobDeliveryMock struct {
	mock.Mock
}

type JobDeliveryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobDeliveryMock) EXPECT() *JobDeliveryMock_Expecter {
	return &JobDeliveryMock_Expecter{mock: &_m.Mock}
}

// Acknowledge provides a mock function for the type JobDeliveryMock
func (_mock *JobDeliveryMock) Acknowledge(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acknowledge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobDeliveryMock_Acknowledge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acknowledge'
type JobDeliveryMock_Acknowledge_Call struct {
	*mock.Call
}

// Acknowledge is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobDeliveryMock_Expecter) Acknowledge(ctx any) *JobDeliveryMock_Acknowledge_Call {
	return &JobDeliveryMock_Acknowledge_Call{Call: _e.mock.On("Acknowledge", ctx)}
}

func (_c *JobDeliveryMock_Acknowledge_Call) Run(run func(ctx context.Context)) *JobDeliveryMock_Acknowledge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobDeliveryMock_Acknowledge_Call) Return(err error) *JobDeliveryMock_Acknowledge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobDeliveryMock_Acknowledge_Call) RunAndReturn(run func(ctx context.Context) error) *JobDeliveryMock_Acknowledge_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type JobDeliveryMock
func (_mock *JobDeliveryMock) Fail(ctx context.Context, err error) error {
	ret := _mock.Called(ctx, err)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, error) error); ok {
		r0 = returnFunc(ctx, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobDeliveryMock_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type JobDeliveryMock_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *JobDeliveryMock_Expecter) Fail(ctx any, err any) *JobDeliveryMock_Fail_Call {
	return &JobDeliveryMock_Fail_Call{Call: _e.mock.On("Fail", ctx, err)}
}

func (_c *JobDeliveryMock_Fail_Call) Run(run func(ctx context.Context, err error)) *JobDeliveryMock_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobDeliveryMock_Fail_Call) Return(err1 error) *JobDeliveryMock_Fail_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *JobDeliveryMock_Fail_Call) RunAndReturn(run func(ctx context.Context, err error) error) *JobDeliveryMock_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type JobDeliveryMock
func (_mock *JobDeliveryMock) Message() contract.JobMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 contract.JobMessage
	if returnFunc, ok := ret.Get(0).(func() contract.JobMessage); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(contract.JobMessage)
	}
	return r0
}

// JobDeliveryMock_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type JobDeliveryMock_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *JobDeliveryMock_Expecter) Message() *JobDeliveryMock_Message_Call {
	return &JobDeliveryMock_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *JobDeliveryMock_Message_Call) Run(run func()) *JobDeliveryMock_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobDeliveryMock_Message_Call) Return(jobMessage contract.JobMessage) *JobDeliveryMock_Message_Call {
	_c.Call.Return(jobMessage)
	return _c
}

func (_c *JobDeliveryMock_Message_Call) RunAndReturn(run func() contract.JobMessage) *JobDeliveryMock_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type JobDeliveryMock
func (_mock *JobDeliveryMock) Reject(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobDeliveryMock_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type JobDeliveryMock_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
func (_e *JobDeliveryMock_Expecter) Reject(ctx any) *JobDeliveryMock_Reject_Call {
	return &JobDeliveryMock_Reject_Call{Call: _e.mock.On("Reject", ctx)}
}

func (_c *JobDeliveryMock_Reject_Call) Run(run func(ctx context.Context)) *JobDeliveryMock_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobDeliveryMock_Reject_Call) Return(err error) *JobDeliveryMock_Reject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobDeliveryMock_Reject_Call) RunAndReturn(run func(ctx context.Context) error) *JobDeliveryMock_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// Retry provides a mock function for the type JobDeliveryMock
func (_mock *JobDeliveryMock) Retry(ctx context.Context, delay time.Duration) error {
	ret := _mock.Called(ctx, delay)

	if len(ret) == 0 {
		panic("no return value specified for Retry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = returnFunc(ctx, delay)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobDeliveryMock_Retry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retry'
type JobDeliveryMock_Retry_Call struct {
	*mock.Call
}

// Retry is a helper method to define mock.On call
//   - ctx context.Context
//   - delay time.Duration
func (_e *JobDeliveryMock_Expecter) Retry(ctx any, delay any) *JobDeliveryMock_Retry_Call {
	return &JobDeliveryMock_Retry_Call{Call: _e.mock.On("Retry", ctx, delay)}
}

func (_c *JobDeliveryMock_Retry_Call) Run(run func(ctx context.Context, delay time.Duration)) *JobDeliveryMock_Retry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobDeliveryMock_Retry_Call) Return(err error) *JobDeliveryMock_Retry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobDeliveryMock_Retry_Call) RunAndReturn(run func(ctx context.Context, delay time.Duration) error) *JobDeliveryMock_Retry_Call {
	_c.Call.Return(run)
	return _c
}

// NewJobConsumerDriverMock creates a new instance of JobConsumerDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobConsumerDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobConsumerDriverMock {
	mock := &JobConsumerDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobConsumerDriverMock is an autogenerated mock type for the JobConsumerDriver type
type JobConsumerDriverMock struct {
	mock.Mock
}

type JobConsumerDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobConsumerDriverMock) EXPECT() *JobConsumerDriverMock_Expecter {
	return &JobConsumerDriverMock_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type JobConsumerDriverMock
func (_mock *JobConsumerDriverMock) Consume(ctx context.Context, queue string, handler contract.JobDeliveryHandler) error {
	ret := _mock.Called(ctx, queue, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, contract.JobDeliveryHandler) error); ok {
		r0 = returnFunc(ctx, queue, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobConsumerDriverMock_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type JobConsumerDriverMock_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - queue string
//   - handler contract.JobDeliveryHandler
func (_e *JobConsumerDriverMock_Expecter) Consume(ctx any, queue any, handler any) *JobConsumerDriverMock_Consume_Call {
	return &JobConsumerDriverMock_Consume_Call{Call: _e.mock.On("Consume", ctx, queue, handler)}
}

func (_c *JobConsumerDriverMock_Consume_Call) Run(run func(ctx context.Context, queue string, handler contract.JobDeliveryHandler)) *JobConsumerDriverMock_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 contract.JobDeliveryHandler
		if args[2] != nil {
			arg2 = args[2].(contract.JobDeliveryHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JobConsumerDriverMock_Consume_Call) Return(err error) *JobConsumerDriverMock_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobConsumerDriverMock_Consume_Call) RunAndReturn(run func(ctx context.Context, queue string, handler contract.JobDeliveryHandler) error) *JobConsumerDriverMock_Consume_Call {
	_c.Call.Return(run)
	return _c
}
