// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewCloserMock creates a new instance of CloserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloserMock {
	mock := &CloserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CloserMock is an autogenerated mock type for the Closer type
type CloserMock struct {
	mock.Mock
}

type CloserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CloserMock) EXPECT() *CloserMock_Expecter {
	return &CloserMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type CloserMock
func (_mock *CloserMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CloserMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CloserMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CloserMock_Expecter) Close() *CloserMock_Close_Call {
	return &CloserMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CloserMock_Close_Call) Run(run func()) *CloserMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CloserMock_Close_Call) Return(err error) *CloserMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CloserMock_Close_Call) RunAndReturn(run func() error) *CloserMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewPingerMock creates a new instance of PingerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingerMock {
	mock := &PingerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PingerMock is an autogenerated mock type for the Pinger type
type PingerMock struct {
	mock.Mock
}

type PingerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PingerMock) EXPECT() *PingerMock_Expecter {
	return &PingerMock_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type PingerMock
func (_mock *PingerMock) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PingerMock_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type PingerMock_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PingerMock_Expecter) Ping(ctx any) *PingerMock_Ping_Call {
	return &PingerMock_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *PingerMock_Ping_Call) Run(run func(ctx context.Context)) *PingerMock_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PingerMock_Ping_Call) Return(err error) *PingerMock_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PingerMock_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *PingerMock_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewShutdownerMock creates a new instance of ShutdownerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShutdownerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShutdownerMock {
	mock := &ShutdownerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShutdownerMock is an autogenerated mock type for the Shutdowner type
type ShutdownerMock struct {
	mock.Mock
}

type ShutdownerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ShutdownerMock) EXPECT() *ShutdownerMock_Expecter {
	return &ShutdownerMock_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function for the type ShutdownerMock
func (_mock *ShutdownerMock) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ShutdownerMock_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ShutdownerMock_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ShutdownerMock_Expecter) Shutdown(ctx any) *ShutdownerMock_Shutdown_Call {
	return &ShutdownerMock_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *ShutdownerMock_Shutdown_Call) Run(run func(ctx context.Context)) *ShutdownerMock_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShutdownerMock_Shutdown_Call) Return(err error) *ShutdownerMock_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ShutdownerMock_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *ShutdownerMock_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
