// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
)

// NewLoggerDriverMock creates a new instance of LoggerDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerDriverMock {
	mock := &LoggerDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LoggerDriverMock is an autogenerated mock type for the LoggerDriver type
type LoggerDriverMock struct {
	mock.Mock
}

type LoggerDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerDriverMock) EXPECT() *LoggerDriverMock_Expecter {
	return &LoggerDriverMock_Expecter{mock: &_m.Mock}
}

// DebugContext provides a mock function for the type LoggerDriverMock
func (_mock *LoggerDriverMock) DebugContext(ctx context.Context, message string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, message, args)
	} else {
		_mock.Called(ctx, message)
	}

	return
}

// LoggerDriverMock_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type LoggerDriverMock_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - args ...any
func (_e *LoggerDriverMock_Expecter) DebugContext(ctx any, message any, args ...any) *LoggerDriverMock_DebugContext_Call {
	return &LoggerDriverMock_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]any{ctx, message}, args...)...)}
}

func (_c *LoggerDriverMock_DebugContext_Call) Run(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LoggerDriverMock_DebugContext_Call) Return() *LoggerDriverMock_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerDriverMock_DebugContext_Call) RunAndReturn(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_DebugContext_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type LoggerDriverMock
func (_mock *LoggerDriverMock) ErrorContext(ctx context.Context, message string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, message, args)
	} else {
		_mock.Called(ctx, message)
	}

	return
}

// LoggerDriverMock_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type LoggerDriverMock_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - args ...any
func (_e *LoggerDriverMock_Expecter) ErrorContext(ctx any, message any, args ...any) *LoggerDriverMock_ErrorContext_Call {
	return &LoggerDriverMock_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]any{ctx, message}, args...)...)}
}

func (_c *LoggerDriverMock_ErrorContext_Call) Run(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LoggerDriverMock_ErrorContext_Call) Return() *LoggerDriverMock_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerDriverMock_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type LoggerDriverMock
func (_mock *LoggerDriverMock) InfoContext(ctx context.Context, message string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, message, args)
	} else {
		_mock.Called(ctx, message)
	}

	return
}

// LoggerDriverMock_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type LoggerDriverMock_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - args ...any
func (_e *LoggerDriverMock_Expecter) InfoContext(ctx any, message any, args ...any) *LoggerDriverMock_InfoContext_Call {
	return &LoggerDriverMock_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]any{ctx, message}, args...)...)}
}

func (_c *LoggerDriverMock_InfoContext_Call) Run(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LoggerDriverMock_InfoContext_Call) Return() *LoggerDriverMock_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerDriverMock_InfoContext_Call) RunAndReturn(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_InfoContext_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type LoggerDriverMock
func (_mock *LoggerDriverMock) WarnContext(ctx context.Context, message string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, message, args)
	} else {
		_mock.Called(ctx, message)
	}

	return
}

// LoggerDriverMock_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type LoggerDriverMock_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - args ...any
func (_e *LoggerDriverMock_Expecter) WarnContext(ctx any, message any, args ...any) *LoggerDriverMock_WarnContext_Call {
	return &LoggerDriverMock_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]any{ctx, message}, args...)...)}
}

func (_c *LoggerDriverMock_WarnContext_Call) Run(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LoggerDriverMock_WarnContext_Call) Return() *LoggerDriverMock_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerDriverMock_WarnContext_Call) RunAndReturn(run func(ctx context.Context, message string, args ...any)) *LoggerDriverMock_WarnContext_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type LoggerDriverMock
func (_mock *LoggerDriverMock) With(args ...any) contract.LoggerDriver {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 contract.LoggerDriver
	if returnFunc, ok := ret.Get(0).(func(...any) contract.LoggerDriver); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.LoggerDriver)
		}
	}
	return r0
}

// LoggerDriverMock_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type LoggerDriverMock_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...any
func (_e *LoggerDriverMock_Expecter) With(args ...any) *LoggerDriverMock_With_Call {
	return &LoggerDriverMock_With_Call{Call: _e.mock.On("With",
		append([]any{}, args...)...)}
}

func (_c *LoggerDriverMock_With_Call) Run(run func(args ...any)) *LoggerDriverMock_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *LoggerDriverMock_With_Call) Return(loggerDriver contract.LoggerDriver) *LoggerDriverMock_With_Call {
	_c.Call.Return(loggerDriver)
	return _c
}

func (_c *LoggerDriverMock_With_Call) RunAndReturn(run func(args ...any) contract.LoggerDriver) *LoggerDriverMock_With_Call {
	_c.Call.Return(run)
	return _c
}
