// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCursorEncoderMock creates a new instance of CursorEncoderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCursorEncoderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CursorEncoderMock {
	mock := &CursorEncoderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CursorEncoderMock is an autogenerated mock type for the CursorEncoder type
type CursorEncoderMock struct {
	mock.Mock
}

type CursorEncoderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CursorEncoderMock) EXPECT() *CursorEncoderMock_Expecter {
	return &CursorEncoderMock_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type CursorEncoderMock
func (_mock *CursorEncoderMock) Encode(value any) (string, error) {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (string, error)); ok {
		return returnFunc(value)
	}
	if returnFunc, ok := ret.Get(0).(func(any) string); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CursorEncoderMock_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type CursorEncoderMock_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - value any
func (_e *CursorEncoderMock_Expecter) Encode(value interface{}) *CursorEncoderMock_Encode_Call {
	return &CursorEncoderMock_Encode_Call{Call: _e.mock.On("Encode", value)}
}

func (_c *CursorEncoderMock_Encode_Call) Run(run func(value any)) *CursorEncoderMock_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0])
	})
	return _c
}

func (_c *CursorEncoderMock_Encode_Call) Return(_a0 string, _a1 error) *CursorEncoderMock_Encode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CursorEncoderMock_Encode_Call) RunAndReturn(run func(any) (string, error)) *CursorEncoderMock_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function for the type CursorEncoderMock
func (_mock *CursorEncoderMock) Decode(cursor string) (any, error) {
	ret := _mock.Called(cursor)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CursorEncoderMock_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type CursorEncoderMock_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - cursor string
func (_e *CursorEncoderMock_Expecter) Decode(cursor interface{}) *CursorEncoderMock_Decode_Call {
	return &CursorEncoderMock_Decode_Call{Call: _e.mock.On("Decode", cursor)}
}

func (_c *CursorEncoderMock_Decode_Call) Run(run func(cursor string)) *CursorEncoderMock_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CursorEncoderMock_Decode_Call) Return(_a0 any, _a1 error) *CursorEncoderMock_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CursorEncoderMock_Decode_Call) RunAndReturn(run func(string) (any, error)) *CursorEncoderMock_Decode_Call {
	_c.Call.Return(run)
	return _c
}
