// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretDriverMock creates a new instance of SecretDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretDriverMock {
	mock := &SecretDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretDriverMock is an autogenerated mock type for the SecretDriver type
type SecretDriverMock struct {
	mock.Mock
}

type SecretDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretDriverMock) EXPECT() *SecretDriverMock_Expecter {
	return &SecretDriverMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type SecretDriverMock
func (_mock *SecretDriverMock) Get(ctx context.Context, name string) ([]byte, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretDriverMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SecretDriverMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *SecretDriverMock_Expecter) Get(ctx any, name any) *SecretDriverMock_Get_Call {
	return &SecretDriverMock_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *SecretDriverMock_Get_Call) Run(run func(ctx context.Context, name string)) *SecretDriverMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretDriverMock_Get_Call) Return(bytes []byte, err error) *SecretDriverMock_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *SecretDriverMock_Get_Call) RunAndReturn(run func(ctx context.Context, name string) ([]byte, error)) *SecretDriverMock_Get_Call {
	_c.Call.Return(run)
	return _c
}
