// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
	"time"
)

// NewSessionMock creates a new instance of SessionMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionMock {
	mock := &SessionMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionMock is an autogenerated mock type for the Session type
type SessionMock struct {
	mock.Mock
}

type SessionMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionMock) EXPECT() *SessionMock_Expecter {
	return &SessionMock_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type SessionMock
func (_mock *SessionMock) Clear() {
	_mock.Called()
	return
}

// SessionMock_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type SessionMock_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *SessionMock_Expecter) Clear() *SessionMock_Clear_Call {
	return &SessionMock_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *SessionMock_Clear_Call) Run(run func()) *SessionMock_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_Clear_Call) Return() *SessionMock_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionMock_Clear_Call) RunAndReturn(run func()) *SessionMock_Clear_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type SessionMock
func (_mock *SessionMock) Delete(key string) {
	_mock.Called(key)
	return
}

// SessionMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *SessionMock_Expecter) Delete(key interface{}) *SessionMock_Delete_Call {
	return &SessionMock_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *SessionMock_Delete_Call) Run(run func(key string)) *SessionMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionMock_Delete_Call) Return() *SessionMock_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionMock_Delete_Call) RunAndReturn(run func(key string)) *SessionMock_Delete_Call {
	_c.Run(run)
	return _c
}

// ExpiresAt provides a mock function for the type SessionMock
func (_mock *SessionMock) ExpiresAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpiresAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// SessionMock_ExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpiresAt'
type SessionMock_ExpiresAt_Call struct {
	*mock.Call
}

// ExpiresAt is a helper method to define mock.On call
func (_e *SessionMock_Expecter) ExpiresAt() *SessionMock_ExpiresAt_Call {
	return &SessionMock_ExpiresAt_Call{Call: _e.mock.On("ExpiresAt")}
}

func (_c *SessionMock_ExpiresAt_Call) Run(run func()) *SessionMock_ExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_ExpiresAt_Call) Return(time1 time.Time) *SessionMock_ExpiresAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *SessionMock_ExpiresAt_Call) RunAndReturn(run func() time.Time) *SessionMock_ExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// ExpiresSoon provides a mock function for the type SessionMock
func (_mock *SessionMock) ExpiresSoon(delta time.Duration) bool {
	ret := _mock.Called(delta)

	if len(ret) == 0 {
		panic("no return value specified for ExpiresSoon")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Duration) bool); ok {
		r0 = returnFunc(delta)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SessionMock_ExpiresSoon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpiresSoon'
type SessionMock_ExpiresSoon_Call struct {
	*mock.Call
}

// ExpiresSoon is a helper method to define mock.On call
//   - delta time.Duration
func (_e *SessionMock_Expecter) ExpiresSoon(delta interface{}) *SessionMock_ExpiresSoon_Call {
	return &SessionMock_ExpiresSoon_Call{Call: _e.mock.On("ExpiresSoon", delta)}
}

func (_c *SessionMock_ExpiresSoon_Call) Run(run func(delta time.Duration)) *SessionMock_ExpiresSoon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionMock_ExpiresSoon_Call) Return(b bool) *SessionMock_ExpiresSoon_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SessionMock_ExpiresSoon_Call) RunAndReturn(run func(delta time.Duration) bool) *SessionMock_ExpiresSoon_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type SessionMock
func (_mock *SessionMock) Extend(expiresAt time.Time) {
	_mock.Called(expiresAt)
	return
}

// SessionMock_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type SessionMock_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
//   - expiresAt time.Time
func (_e *SessionMock_Expecter) Extend(expiresAt interface{}) *SessionMock_Extend_Call {
	return &SessionMock_Extend_Call{Call: _e.mock.On("Extend", expiresAt)}
}

func (_c *SessionMock_Extend_Call) Run(run func(expiresAt time.Time)) *SessionMock_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionMock_Extend_Call) Return() *SessionMock_Extend_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionMock_Extend_Call) RunAndReturn(run func(expiresAt time.Time)) *SessionMock_Extend_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type SessionMock
func (_mock *SessionMock) Get(key string) (any, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// SessionMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *SessionMock_Expecter) Get(key interface{}) *SessionMock_Get_Call {
	return &SessionMock_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *SessionMock_Get_Call) Run(run func(key string)) *SessionMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionMock_Get_Call) Return(v any, b bool) *SessionMock_Get_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *SessionMock_Get_Call) RunAndReturn(run func(key string) (any, bool)) *SessionMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HasChanged provides a mock function for the type SessionMock
func (_mock *SessionMock) HasChanged() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasChanged")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SessionMock_HasChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChanged'
type SessionMock_HasChanged_Call struct {
	*mock.Call
}

// HasChanged is a helper method to define mock.On call
func (_e *SessionMock_Expecter) HasChanged() *SessionMock_HasChanged_Call {
	return &SessionMock_HasChanged_Call{Call: _e.mock.On("HasChanged")}
}

func (_c *SessionMock_HasChanged_Call) Run(run func()) *SessionMock_HasChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_HasChanged_Call) Return(b bool) *SessionMock_HasChanged_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SessionMock_HasChanged_Call) RunAndReturn(run func() bool) *SessionMock_HasChanged_Call {
	_c.Call.Return(run)
	return _c
}

// HasExpired provides a mock function for the type SessionMock
func (_mock *SessionMock) HasExpired() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasExpired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SessionMock_HasExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasExpired'
type SessionMock_HasExpired_Call struct {
	*mock.Call
}

// HasExpired is a helper method to define mock.On call
func (_e *SessionMock_Expecter) HasExpired() *SessionMock_HasExpired_Call {
	return &SessionMock_HasExpired_Call{Call: _e.mock.On("HasExpired")}
}

func (_c *SessionMock_HasExpired_Call) Run(run func()) *SessionMock_HasExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_HasExpired_Call) Return(b bool) *SessionMock_HasExpired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SessionMock_HasExpired_Call) RunAndReturn(run func() bool) *SessionMock_HasExpired_Call {
	_c.Call.Return(run)
	return _c
}

// HasRegenerated provides a mock function for the type SessionMock
func (_mock *SessionMock) HasRegenerated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasRegenerated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SessionMock_HasRegenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRegenerated'
type SessionMock_HasRegenerated_Call struct {
	*mock.Call
}

// HasRegenerated is a helper method to define mock.On call
func (_e *SessionMock_Expecter) HasRegenerated() *SessionMock_HasRegenerated_Call {
	return &SessionMock_HasRegenerated_Call{Call: _e.mock.On("HasRegenerated")}
}

func (_c *SessionMock_HasRegenerated_Call) Run(run func()) *SessionMock_HasRegenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_HasRegenerated_Call) Return(b bool) *SessionMock_HasRegenerated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SessionMock_HasRegenerated_Call) RunAndReturn(run func() bool) *SessionMock_HasRegenerated_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsUnchanged provides a mock function for the type SessionMock
func (_mock *SessionMock) MarkAsUnchanged() {
	_mock.Called()
	return
}

// SessionMock_MarkAsUnchanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsUnchanged'
type SessionMock_MarkAsUnchanged_Call struct {
	*mock.Call
}

// MarkAsUnchanged is a helper method to define mock.On call
func (_e *SessionMock_Expecter) MarkAsUnchanged() *SessionMock_MarkAsUnchanged_Call {
	return &SessionMock_MarkAsUnchanged_Call{Call: _e.mock.On("MarkAsUnchanged")}
}

func (_c *SessionMock_MarkAsUnchanged_Call) Run(run func()) *SessionMock_MarkAsUnchanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_MarkAsUnchanged_Call) Return() *SessionMock_MarkAsUnchanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionMock_MarkAsUnchanged_Call) RunAndReturn(run func()) *SessionMock_MarkAsUnchanged_Call {
	_c.Run(run)
	return _c
}

// OriginalSessionID provides a mock function for the type SessionMock
func (_mock *SessionMock) OriginalSessionID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OriginalSessionID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SessionMock_OriginalSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OriginalSessionID'
type SessionMock_OriginalSessionID_Call struct {
	*mock.Call
}

// OriginalSessionID is a helper method to define mock.On call
func (_e *SessionMock_Expecter) OriginalSessionID() *SessionMock_OriginalSessionID_Call {
	return &SessionMock_OriginalSessionID_Call{Call: _e.mock.On("OriginalSessionID")}
}

func (_c *SessionMock_OriginalSessionID_Call) Run(run func()) *SessionMock_OriginalSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_OriginalSessionID_Call) Return(s string) *SessionMock_OriginalSessionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SessionMock_OriginalSessionID_Call) RunAndReturn(run func() string) *SessionMock_OriginalSessionID_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type SessionMock
func (_mock *SessionMock) Put(key string, value any) {
	_mock.Called(key, value)
	return
}

// SessionMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type SessionMock_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *SessionMock_Expecter) Put(key interface{}, value interface{}) *SessionMock_Put_Call {
	return &SessionMock_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *SessionMock_Put_Call) Run(run func(key string, value any)) *SessionMock_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionMock_Put_Call) Return() *SessionMock_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *SessionMock_Put_Call) RunAndReturn(run func(key string, value any)) *SessionMock_Put_Call {
	_c.Run(run)
	return _c
}

// Regenerate provides a mock function for the type SessionMock
func (_mock *SessionMock) Regenerate(expiresAt time.Time) error {
	ret := _mock.Called(expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Regenerate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionMock_Regenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Regenerate'
type SessionMock_Regenerate_Call struct {
	*mock.Call
}

// Regenerate is a helper method to define mock.On call
//   - expiresAt time.Time
func (_e *SessionMock_Expecter) Regenerate(expiresAt interface{}) *SessionMock_Regenerate_Call {
	return &SessionMock_Regenerate_Call{Call: _e.mock.On("Regenerate", expiresAt)}
}

func (_c *SessionMock_Regenerate_Call) Run(run func(expiresAt time.Time)) *SessionMock_Regenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SessionMock_Regenerate_Call) Return(err error) *SessionMock_Regenerate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionMock_Regenerate_Call) RunAndReturn(run func(expiresAt time.Time) error) *SessionMock_Regenerate_Call {
	_c.Call.Return(run)
	return _c
}

// SessionID provides a mock function for the type SessionMock
func (_mock *SessionMock) SessionID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SessionMock_SessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionID'
type SessionMock_SessionID_Call struct {
	*mock.Call
}

// SessionID is a helper method to define mock.On call
func (_e *SessionMock_Expecter) SessionID() *SessionMock_SessionID_Call {
	return &SessionMock_SessionID_Call{Call: _e.mock.On("SessionID")}
}

func (_c *SessionMock_SessionID_Call) Run(run func()) *SessionMock_SessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionMock_SessionID_Call) Return(s string) *SessionMock_SessionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SessionMock_SessionID_Call) RunAndReturn(run func() string) *SessionMock_SessionID_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionDriverMock creates a new instance of SessionDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionDriverMock {
	mock := &SessionDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionDriverMock is an autogenerated mock type for the SessionDriver type
type SessionDriverMock struct {
	mock.Mock
}

type SessionDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionDriverMock) EXPECT() *SessionDriverMock_Expecter {
	return &SessionDriverMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionDriverMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionDriverMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionDriverMock_Expecter) Delete(ctx interface{}, id interface{}) *SessionDriverMock_Delete_Call {
	return &SessionDriverMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SessionDriverMock_Delete_Call) Run(run func(ctx context.Context, id string)) *SessionDriverMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Delete_Call) Return(err error) *SessionDriverMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionDriverMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *SessionDriverMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Get(ctx context.Context, id string) (contract.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 contract.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (contract.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) contract.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contract.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionDriverMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionDriverMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionDriverMock_Expecter) Get(ctx interface{}, id interface{}) *SessionDriverMock_Get_Call {
	return &SessionDriverMock_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *SessionDriverMock_Get_Call) Run(run func(ctx context.Context, id string)) *SessionDriverMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Get_Call) Return(session contract.Session, err error) *SessionDriverMock_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionDriverMock_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (contract.Session, error)) *SessionDriverMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Save(ctx context.Context, session contract.Session, ttl time.Duration) error {
	ret := _mock.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, contract.Session, time.Duration) error); ok {
		r0 = returnFunc(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionDriverMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionDriverMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session contract.Session
//   - ttl time.Duration
func (_e *SessionDriverMock_Expecter) Save(ctx interface{}, session interface{}, ttl interface{}) *SessionDriverMock_Save_Call {
	return &SessionDriverMock_Save_Call{Call: _e.mock.On("Save", ctx, session, ttl)}
}

func (_c *SessionDriverMock_Save_Call) Run(run func(ctx context.Context, session contract.Session, ttl time.Duration)) *SessionDriverMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 contract.Session
		if args[1] != nil {
			arg1 = args[1].(contract.Session)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Save_Call) Return(err error) *SessionDriverMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionDriverMock_Save_Call) RunAndReturn(run func(ctx context.Context, session contract.Session, ttl time.Duration) error) *SessionDriverMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
