// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"github.com/studiolambda/cosmos/contract"
	"time"
)

// NewSessionDriverMock creates a new instance of SessionDriverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionDriverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionDriverMock {
	mock := &SessionDriverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionDriverMock is an autogenerated mock type for the SessionDriver type
type SessionDriverMock struct {
	mock.Mock
}

type SessionDriverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionDriverMock) EXPECT() *SessionDriverMock_Expecter {
	return &SessionDriverMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionDriverMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionDriverMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionDriverMock_Expecter) Delete(ctx any, id any) *SessionDriverMock_Delete_Call {
	return &SessionDriverMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SessionDriverMock_Delete_Call) Run(run func(ctx context.Context, id string)) *SessionDriverMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Delete_Call) Return(err error) *SessionDriverMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionDriverMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *SessionDriverMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Get(ctx context.Context, id string) (*contract.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *contract.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*contract.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *contract.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionDriverMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionDriverMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *SessionDriverMock_Expecter) Get(ctx any, id any) *SessionDriverMock_Get_Call {
	return &SessionDriverMock_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *SessionDriverMock_Get_Call) Run(run func(ctx context.Context, id string)) *SessionDriverMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Get_Call) Return(session *contract.Session, err error) *SessionDriverMock_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionDriverMock_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*contract.Session, error)) *SessionDriverMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SessionDriverMock
func (_mock *SessionDriverMock) Save(ctx context.Context, session *contract.Session, ttl time.Duration) error {
	ret := _mock.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *contract.Session, time.Duration) error); ok {
		r0 = returnFunc(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionDriverMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionDriverMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session *contract.Session
//   - ttl time.Duration
func (_e *SessionDriverMock_Expecter) Save(ctx any, session any, ttl any) *SessionDriverMock_Save_Call {
	return &SessionDriverMock_Save_Call{Call: _e.mock.On("Save", ctx, session, ttl)}
}

func (_c *SessionDriverMock_Save_Call) Run(run func(ctx context.Context, session *contract.Session, ttl time.Duration)) *SessionDriverMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *contract.Session
		if args[1] != nil {
			arg1 = args[1].(*contract.Session)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionDriverMock_Save_Call) Return(err error) *SessionDriverMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionDriverMock_Save_Call) RunAndReturn(run func(ctx context.Context, session *contract.Session, ttl time.Duration) error) *SessionDriverMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
