package problem

import (
	"encoding/json/v2"
	"fmt"
	"maps"
	"net/http"
	"strings"

	"github.com/studiolambda/cosmos/problem/internal"
)

// Details represents a problem details response for HTTP APIs.
// It implements [error] and [http.Handler].
// See https://datatracker.ietf.org/doc/html/rfc9457 for more information.
type Details struct {

	// err stores the native error of the problem if
	// it happens to have one. This struct member can be
	// nil if the problem was created manually.
	//
	// Refer to [NewDetails] to automatically assign an error
	// to the new Details.
	err error

	// Additional stores RFC 9457 extension members. Its entries are embedded
	// as top-level JSON properties rather than serialized under "Additional".
	// Unknown top-level JSON properties are also stored here when unmarshaling.
	Additional map[string]any `json:",embed"`

	// Type member is a JSON string containing a URI reference
	// that identifies the problem type.
	//
	// Consumers MUST use the Type URI (after resolution,
	// if necessary) as the problem type's primary identifier.
	//
	// When this member is not present, its value is assumed
	// to be "about:blank".
	Type string `json:"type"`

	// Title member is a string containing a short,
	// human-readable summary of the problem type.
	//
	// It SHOULD NOT change from occurrence to occurrence of
	// the problem, except for localization (e.g., using proactive
	// content negotiation.
	//
	// The Title string is advisory and is included only for users
	// who are unaware of and cannot discover the semantics of the
	// type URI (e.g., during offline log analysis).
	Title string `json:"title"`

	// Detail member is a JSON string containing a human-readable
	// explanation specific to this occurrence of the problem.
	//
	// The Detail string, if present, ought to focus on helping
	// the client correct the problem, rather than giving debugging information.
	//
	// Consumers SHOULD NOT parse the Detail member for information.
	//
	// Extensions are more suitable and less error-prone ways to obtain
	// such information.
	Detail string `json:"detail"`

	// The Status member is a JSON number indicating the HTTP status
	// code generated by the origin server for this occurrence of the problem.
	//
	// The "status" member, if present, is only advisory; it conveys the HTTP
	// status code used for the convenience of the consumer.
	//
	// Generators MUST use the same status code in the actual HTTP response,
	// to assure that generic HTTP software that does not understand this format
	// still behaves correctly.
	//
	// Consumers can use the status member to determine what the original status
	// code used by the generator was when it has been changed
	// (e.g., by an intermediary or cache) and when a message's content is
	// persisted without HTTP information. Generic HTTP software will still
	// use the HTTP status code.
	Status int `json:"status"`

	// The "instance" member is a JSON string containing a URI reference that
	// identifies the specific occurrence of the problem.
	//
	// When the "instance" URI is dereferenceable, the problem details object
	// can be fetched from it. It might also return information about the problem
	// occurrence in other formats through use of proactive content negotiation.
	//
	// When the "instance" URI is not dereferenceable, it serves as a unique identifier
	// for the problem occurrence that may be of significance to the server but is
	// opaque to the client.
	//
	// When "instance" contains a relative URI, it is resolved relative to the document's
	// base URI. However, using relative URIs can cause confusion, and they might not
	// be handled correctly by all implementations.
	//
	// For example, if the two resources "https://api.example.org/foo/bar/123"
	// and "https://api.example.org/widget/456" both respond with an "instance" equal
	// to the relative URI reference "example-instance", when resolved they will
	// identify different resources ("https://api.example.org/foo/bar/example-instance"
	// and "https://api.example.org/widget/example-instance", respectively).
	//
	// As a result, it is RECOMMENDED that absolute URIs be used in "instance" when possible,
	// and that when relative URIs are used, they include the full path (e.g., "/instances/123").
	Instance string `json:"instance"`
}

// NewDetails creates a new [Details] from
// the given error and status code.
//
// For application code, prefer defining reusable package-level
// [Details] templates (for example, var ErrUserNotFound = problem.Details{...})
// and deriving request-specific values with [Details.WithError] and [Details.With].
// Use NewDetails mainly for adapter/integration boundaries where no reusable
// template exists.
func NewDetails(err error, status int) Details {
	return Details{
		err:    err,
		Status: status,
	}
}

// WithType returns a new [Details] with the given type URI.
// The original [Details] is not modified.
func (problem Details) WithType(problemType string) Details {
	problem.Type = problemType

	return problem
}

// WithTitle returns a new [Details] with the given human-readable title.
// The original [Details] is not modified.
func (problem Details) WithTitle(title string) Details {
	problem.Title = title

	return problem
}

// WithDetail returns a new [Details] with the given occurrence-specific detail.
// The original [Details] is not modified.
func (problem Details) WithDetail(detail string) Details {
	problem.Detail = detail

	return problem
}

// WithStatus returns a new [Details] with the given HTTP status code.
// The original [Details] is not modified.
func (problem Details) WithStatus(status int) Details {
	problem.Status = status

	return problem
}

// WithInstance returns a new [Details] with the given problem instance URI.
// The original [Details] is not modified.
func (problem Details) WithInstance(instance string) Details {
	problem.Instance = instance

	return problem
}

// With returns a new [Details] with an additional value set for the given key.
// The original [Details] is not modified (copy-on-write).
// Use [Details.Without] to remove additional values.
//
// Example:
//
//	p := ErrValidation.With("resource_id", 42)
//	_ = p
func (problem Details) With(key string, value any) Details {
	if problem.Additional == nil {
		problem.Additional = map[string]any{key: value}

		return problem
	}

	problem.Additional = maps.Clone(problem.Additional)
	problem.Additional[key] = value

	return problem
}

// WithError returns a new [Details] with the given error
// set as the underlying cause.
//
// Example:
//
//	p := ErrUserNotFound.WithError(err)
//	_ = p
func (problem Details) WithError(err error) Details {
	problem.err = err

	return problem
}

// WithoutError returns a new [Details] with the error
// that's associated with it removed.
func (problem Details) WithoutError() Details {
	problem.err = nil

	return problem
}

// Without returns a new [Details] with the additional value for the given key removed.
//
// Example:
//
//	p := ErrValidation.With("field", "email")
//	p = p.Without("field")
func (problem Details) Without(key string) Details {
	if problem.Additional == nil {
		return problem
	}

	problem.Additional = maps.Clone(problem.Additional)
	delete(problem.Additional, key)

	return problem
}

// Error returns a string representation of the [Details] for the [error] interface.
func (problem Details) Error() string {
	title := problem.Title

	if title == "" {
		title = http.StatusText(problem.Status)
	}

	if problem.err != nil {
		return fmt.Sprintf("%d %s: %s", problem.Status, title, problem.err)
	}

	return fmt.Sprintf("%d %s", problem.Status, title)
}

// Unwrap returns the underlying error from the [Details]
// for use with [errors.Is] and [errors.As].
func (problem Details) Unwrap() error {
	return problem.err
}

// Defaulted returns a new [Details] with zero-value fields filled with sensible
// defaults: Type defaults to "about:blank", Status to 500, Title to
// [http.StatusText] of the status, and Instance to the request URL path.
//
// Example:
//
//	resolved := p.Defaulted(r)
//	_ = resolved
func (problem Details) Defaulted(request *http.Request) Details {
	if problem.Type == "" {
		problem.Type = "about:blank"
	}

	if problem.Status == 0 {
		problem.Status = http.StatusInternalServerError
	}

	if problem.Title == "" {
		problem.Title = http.StatusText(problem.Status)
	}

	if problem.Instance == "" && request != nil {
		problem.Instance = request.URL.Path
	}

	return problem
}

// textHandler writes the problem as a plain text HTTP response.
func (problem Details) textHandler(w http.ResponseWriter) {
	var b strings.Builder

	fmt.Fprintf(&b, "%d %s\n\n%s", problem.Status, problem.Title, problem.Detail)

	http.Error(w, b.String(), problem.Status)
}

// jsonHandler writes the problem as a standard application/json
// HTTP response.
func (problem Details) jsonHandler(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(problem.Status)

	if encoded, err := json.Marshal(problem); err == nil {
		_, _ = w.Write(append(encoded, '\n'))
	}
}

// jsonProblemHandler writes the problem as an application/problem+json
// HTTP response per RFC 9457.
func (problem Details) jsonProblemHandler(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(problem.Status)

	if encoded, err := json.Marshal(problem); err == nil {
		_, _ = w.Write(append(encoded, '\n'))
	}
}

// ServeHTTP writes the problem as an HTTP response using content
// negotiation. It supports application/problem+json, application/json,
// and falls back to plain text.
//
// Example:
//
//	problem.Details{Status: http.StatusNotFound, Title: "Not Found"}.ServeHTTP(w, r)
func (problem Details) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	problem = problem.withContextValues(r.Context())
	problem = problem.Defaulted(r) // Just in case.
	accept := internal.ParseAccept(r)

	problemQuality := accept.Quality("application/problem+json")
	jsonQuality := accept.Quality("application/json")

	if jsonQuality > 0 && jsonQuality >= problemQuality {
		problem.jsonHandler(w)
		return
	}

	if problemQuality > 0 {
		problem.jsonProblemHandler(w)
		return
	}

	problem.textHandler(w)
}

// HTTPStatus returns the HTTP status code of the problem.
// This is useful for error handlers that need to extract the
// status code from the problem.
//
// Example:
//
//	status := errProblem.HTTPStatus()
//	_ = status
func (problem Details) HTTPStatus() int {
	return problem.Status
}
